[Refactor] Introduce new error event completion handler
Azure/communication-ui-library-ios pull request #212
Opened 2022-05-26 00:10 UTC by JoshuaLai

## Purpose
Introduce a new error event completion handler. 

## Does this introduce a breaking change?
API is not yet public 

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

2022-05-26 18:27 UTC, tjprescott commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/AvatarViewManager.swift
>  }
Why would you not update the protocol to match?

2022-05-26 18:27 UTC, tjprescott commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/AvatarViewManager.swift
> +        participantViewData: ParticipantViewData) -> CommunicationUIErrorEvent? {
Why not refactor this in the same way?

2022-05-26 18:46 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/AvatarViewManager.swift
> +        participantViewData: ParticipantViewData) -> CommunicationUIErrorEvent? {
I think we can update this to follow the same approach as in CallComposite and simplify CallComposite func

2022-05-26 23:24 UTC, tjprescott commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/RemoteParticipantAvatarHelper.swift
> +            }
This should be `set(remoteParticipantViewData: participantViewData, for: identifier) {...`

2022-05-26 23:25 UTC, tjprescott commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
> +    public func setRemoteParticipantViewData(_ participantViewData: ParticipantViewData,
should be `set(remoteParticipantViewData: ParticipantViewData, for identifier: CommunicationIdentifier, ...`

2022-05-26 23:25 UTC, tjprescott commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/AvatarViewManager.swift
> +                                      errorHandler: ((CommunicationUIErrorEvent) -> Void)?)
Same as above.

2022-05-26 23:31 UTC, tjprescott commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/Manager/AvatarViewManager.swift
> +                                      errorHandler: ((CommunicationUIErrorEvent) -> Void)? = nil) {
Same as above. `setFoo(_ foo: Foo)` is the old style Swift. Apple has replaced most of those APIs with `set(foo: Foo)` style APIs.

2022-05-26 23:33 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/RemoteParticipantAvatarHelper.swift
> +            }
updated it to have a little bit more parity with Android

2022-05-27 23:13 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp/RemoteParticipantAvatarHelper.swift
> +            }
@tjprescott Updated to the proposed solution!

2022-05-31 14:38 UTC, tjprescott commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/CommunicationUIErrorEvent.swift
> -public struct CommunicationUIErrorEvent: Error {
Is there a reason you are making this no longer conform to `Error`?

2022-05-31 14:38 UTC, tjprescott commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
> +    public func setRemoteParticipantJoinHandler(with participantsJoinedAction: (([CommunicationIdentifier]) -> Void)?) {
Is this being updated in a separate PR?

2022-05-31 14:38 UTC, tjprescott commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
> +    public func setDidFailHandler(with didFailAction: ((CommunicationUIErrorEvent) -> Void)?) {
Is this being updated in a separate PR?

2022-05-31 15:54 UTC, waynemo requested changes, later dismissed

2022-05-31 15:54 UTC, waynemo commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallCompositeOptions/ParticipantViewDataSetError.swift
> +    case remoteParticipantNotFound = "RemoteParticipantNotFound"
Could we align on the error naming with Android?
https://github.com/Azure/communication-ui-library-android/blob/develop/beta/azure-communication-ui/azure-communication-ui/src/calling/java/com/azure/android/communication/ui/calling/models/SetParticipantViewDataResult.java#L15

2022-05-31 16:21 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
> +    public func setRemoteParticipantJoinHandler(with participantsJoinedAction: (([CommunicationIdentifier]) -> Void)?) {
Yes, I'll share it later today
I've just updated the completion handlers to remove the typealiasess as we agreed

2022-05-31 16:21 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
> +    public func setDidFailHandler(with didFailAction: ((CommunicationUIErrorEvent) -> Void)?) {
Yes, I'll share it later today
I've just updated the completion handlers to remove the typealiasess as we agreed

2022-05-31 17:35 UTC, AmyL219 commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
> +                    completionHandler: ((Result<Void, ParticipantViewDataSetError>) -> Void)? = nil) {
Why do we want to return a `Result` inside the completionHandler? Why not just 
```
completionHandler: (ParticipantViewDataSetError?) -> Void)? = nil)
```

2022-05-31 17:56 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/CallComposite.swift
> +                    completionHandler: ((Result<Void, ParticipantViewDataSetError>) -> Void)? = nil) {
To have a little bit clearer separation between success and failure, and it will allow us to have some kind of parity between iOS and Android but in Swifty way

2022-06-01 18:32 UTC, jimchou-dev submitted a review, later dismissed

2022-06-01 18:53 UTC, jimchou-dev approved these changes

2022-06-01 21:44 UTC, AmyL219 approved these changes

2022-06-01 23:21 UTC, merged