[Refactor] Switch actions to an enumerated types
Azure/communication-ui-library-ios pull request #289
Opened 2022-06-27 20:35 UTC by emlynmac

## Purpose
Currently, the redux implementation is using an open protocol. This allows any object to become an action and forces run time dynamic resolution of actions and functionality.

This PR changes the actions to be a enumeration hierarchy, which enables the compiler to see types at compile time and as a result can ensure that we have the correct actions being handled properly.

The need for class checking at run time is removed, replaced with compile-time checking of enumeration instances with associated data. This removes much of the `if let <value> as? <type>` and associated tests.

## Does this introduce a breaking change?
```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
Follow the usual testing procedure; code functionality should be unchanged.

## What to Check
All functionality should be unchanged.

## Other Information
I will be discussing this PR and related ideas at the meeting tomorrow.

2022-06-28 23:12 UTC, jimchou-dev commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/DI/DependancyContainer.swift
> +        ]
We have it as an array previously also, but can someone help to explain why does this needs to be an array?

2022-06-29 01:03 UTC, JoshuaLai commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Middleware/CallingMiddleware.swift
> +    static func liveCallingMiddleware(callingMiddlewareHandler actionHandler: CallingMiddlewareHandling)
nitpick: I think we can think up of a better name. I am not sure if `liveCallingMiddleware` gives us context to know what this method does. 
Maybe `applyActionHandler`?

2022-06-29 01:06 UTC, JoshuaLai commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Action/Actions.swift
> +enum Actions: Equatable {
minor nitpick: `Actions` I personally would like to see as `Action` this aligns closer with its predecessors name and aligns with the Android implementations name. 
Also IMO it just looks odd cause plural implies its a list so I feel it would look odd if it was `[Actions]`. 
Super minor though

2022-06-29 01:08 UTC, JoshuaLai commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Middleware/CallingMiddleware.swift
> +                                break
I know we discussed about breaking this up into smaller helper methods, but now that this is in a static methodit might not be any more elegant. Just some food for thought here.

2022-06-29 01:13 UTC, JoshuaLai commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Store.swift
> +                let dispatch: (Actions) -> Void = { [unowned self] in self.dispatch(action: $0) }
I believe using `unowned` here is ok cause self should still be there. However as general best practice I think I do still prefer us use `weak` and not risk the off chance of a run time crash.

2022-06-29 01:14 UTC, JoshuaLai commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Reducer/ErrorReducerTests.swift
> +    // No longer possible with compile time state checking
Yep this makes sense. In this case lets just delete this test since it is no longer relevant

2022-06-29 01:17 UTC, JoshuaLai commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Reducer/ErrorReducerTests.swift
> +        // Should set the initial state to something other than the expected state so we know the reducer did something
I assume with this comment you are suggesting a change to this specific unit test to use a different error state? Or perhaps no error state at all? And then update the error state to be `.callDenied`

2022-06-29 01:36 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Middleware/CallingMiddleware.swift
> +    static func liveCallingMiddleware(callingMiddlewareHandler actionHandler: CallingMiddlewareHandling)
The live version of the calling middleware implementation here was the logic for the name.

I could go with  `Middleware.callHandling` maybe?

2022-06-29 01:37 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Action/Actions.swift
> +enum Actions: Equatable {
Yes, completely agree. I deferred the thinking about name until discussion with the group. 
My preference would be something like, `LibraryAction` or `ActionType` just because `Action` is used to specify generics elsewhere.

2022-06-29 01:39 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Middleware/CallingMiddleware.swift
> +                                break
I personally like seeing all the cases clearly.
If we remove the `default` case and implement every un-used case, then it will be a _lot_ of cases and I can see value in breaking out the handlers to other functions.

I'll have a look at both and check in the the one I think looks better, removing the default handlers.

2022-06-29 01:41 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Store.swift
> +                let dispatch: (Actions) -> Void = { [unowned self] in self.dispatch(action: $0) }
The store must always outlive the dispatch. This makes it safe to call unowned and as a result remove the possibility of an optional to handle.

2022-06-29 01:41 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Reducer/ErrorReducerTests.swift
> +    // No longer possible with compile time state checking
Will clean up

2022-06-29 01:42 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICallingTests/Redux/Reducer/ErrorReducerTests.swift
> +        // Should set the initial state to something other than the expected state so we know the reducer did something
Some of the tests were setting the initial state the same as the expected state, which means you don't get a real test. I think this is a comment I wrote to call that out - I'll clean it up.

2022-06-29 18:16 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Action/LocalUserAction.swift
> +        guard type(of: lhs) == type(of: rhs) else {
I'm wondering if this will always return true as `type(of: lhs)` and `type(of: rhs)` will return `LocalUserAction`

2022-06-29 18:16 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Action/LocalUserAction.swift
> +        default:
It would be good to add checks for other cases with Associated Values

2022-06-29 18:16 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/State/RemoteParticipantsState.swift
> +class RemoteParticipantsState {
Should `RemoteParticipantsState` be updated to a struct?

2022-06-29 18:20 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarViewModel.swift
> +            LocalUserAction.cameraOffTriggered : LocalUserAction.cameraOnTriggered
Updated

2022-06-29 18:33 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Action/LocalUserAction.swift
> +        guard type(of: lhs) == type(of: rhs) else {
Good catch! 
Exploring this in a playground does not work as I thought it would. I will rework.

2022-06-29 18:57 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Action/LocalUserAction.swift
> +        default:
Have an update for this as a more general case.

2022-06-29 19:25 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/State/RemoteParticipantsState.swift
> +class RemoteParticipantsState {
Updated

2022-06-29 20:06 UTC, waynemo requested changes, later dismissed

2022-06-29 20:06 UTC, waynemo commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Reducer/Reducer.swift
> +    var reduce: (_ state: State, _ action: Action) -> State
Wondering why we have this as a var instead of an initializer. Do we need to update the `reduce` property?

2022-06-29 20:09 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Reducer/Reducer.swift
> +    var reduce: (_ state: State, _ action: Action) -> State
The var defines the interface for the struct. 
There is no explicit initializer as it depends on context from the generics.
When we use the implicit initializer, it creates the same interface.

2022-06-29 22:20 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Reducer/Reducer.swift
> +    var reduce: (_ state: State, _ action: Action) -> State
Updated after discussion; we're not using the override ability currently so this can be changed to a `let` for now

2022-06-29 23:36 UTC, vhuseinova-msft approved these changes, later dismissed

2022-06-30 15:07 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Action/Actions.swift
> +enum Actions: Equatable {
Ah ha - ok consistency. Will rename to `Action` and change the generic to `ActionType`

2022-06-30 16:23 UTC, AmyL219 commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Reducer/CallingReducer.swift
> +    static var liveCallingReducer: Self = Reducer { callingState, action in
could Reducer be `non-static`?

2022-06-30 16:23 UTC, AmyL219 commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Store.swift
> +    private let reducer: Reducer<State, Action>
This `Action` is still not generic, correct? And we couldn't reuse the Store in ChatComposite with fully flexibility
What if we package the `Store` to a package? I think we have to also package `Action` into the package. otherwise it would throw the warning. But `Action` is only specific to `CallingComposite` in it's definition

2022-06-30 16:45 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Reducer/AppStateReducer.swift
> +            if case let .permissionAction(permAction) = action {
Case let is essentially a switch but then resolving that type to the action.

2022-06-30 16:48 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Reducer/LifeCycleReducer.swift
> +                        Actions == LifecycleAction {
We always want to limit the possible values allowed to a function to the minimal types that it needs. 
Scoping the actions appropriately ensures that we don't need to write unnecessary handlers and also makes it very clear what the scope of the reducing function is.

2022-06-30 17:07 UTC, AmyL219 commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/DI/DependancyContainer.swift
> +        ]
Because we could have more than one middleware in future. 
We could have callMiddleware, we could have audioSessionMiddleware.

2022-06-30 17:09 UTC, AmyL219 commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Reducer/AppStateReducer.swift
> +            if case let .permissionAction(permAction) = action {
`if case let ` should be equal to `if`. So the action would check all those if statement. The performance is same with casting

2022-06-30 17:13 UTC, AmyL219 commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Reducer/LocalUserReducer.swift
> +private func getRequestedDeviceStatus(for audioDeviceType: AudioDeviceType)
I don't feel it's a good practice

2022-06-30 17:38 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Reducer/AppStateReducer.swift
> +            if case let .permissionAction(permAction) = action {
Yes, we can do it that way to avoid a `case let`; but the whole method cannot be wrapped up in a switch as the control flow can mean multiple reducers handle a single action.

2022-06-30 17:44 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Store.swift
> +    private let reducer: Reducer<State, Action>
We would be able to reuse `Store` in `ChatComposite` even without generics but when `ChatComposite` will have its own implementation of `Action`.

2022-06-30 17:44 UTC, vhuseinova-msft approved these changes

2022-06-30 18:42 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Reducer/LocalUserReducer.swift
> +private func getRequestedDeviceStatus(for audioDeviceType: AudioDeviceType)
In general, global writable variables are evil and should be avoided at all times.

This is a file private function, which gives it the same scope as a private method on a class. 
The function is pure and is only applicable to the file.

2022-06-30 20:11 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Middleware/CallingMiddleware.swift
> +    static func liveCallingMiddleware(callingMiddlewareHandler actionHandler: CallingMiddlewareHandling)
Task created for follow up https://skype.visualstudio.com/SPOOL/_sprints/taskboard/ACS%20Mobile%20UI%20-%20iOS/SPOOL/CY2022-Q3/Sprint%2066%20(Ends%20July%2010)?workitem=2912031

2022-06-30 20:29 UTC, emlynmac commented
I've created a task for follow up of some of the discussion points here in https://skype.visualstudio.com/SPOOL/_workitems/edit/2912031

2022-06-30 22:06 UTC, jimchou-dev approved these changes

2022-06-30 22:07 UTC, JoshuaLai approved these changes

2022-06-30 22:08 UTC, kevinyulu approved these changes

2022-06-30 22:32 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling/Redux/Reducer/LocalUserReducer.swift
> +private func getRequestedDeviceStatus(for audioDeviceType: AudioDeviceType)
To be discussed as part of https://skype.visualstudio.com/SPOOL/_workitems/edit/2912031

2022-06-30 22:52 UTC, merged