[Feature] Draft of adding pinch, zoom and pan gestures in video screen share view in a call
Azure/communication-ui-library-ios pull request #29
Opened 2022-01-13 20:09 UTC by kevinyulu

## Purpose
In this PR I drafted the feature supporting user pinch, zoom and pan gestures in video screen share in a call. The functionalities resembles the MS Teams application UX.
Additional features introduced:
* double tap to zoom in / zoom out
* only zooming the actual video content, not the entire rendered view from SDK

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code
* Join a call either using group or Teams call, in iOS app and Teams application (desktop)
* Turn on screenshare in Teams application (desktop)
* Start to perform pinch, zoom and pan gesture on the screen share video 
* Follow **What to Check section**
```

## What to Check
Verify that the following are valid
* Check if the pinch, zoom and pan gestures works in screen share video, in all supported orientations during a call
* Check if double tap to zoom in / out is working as well.

## Other Information

2022-01-18 06:36 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
> +    let getRemoteParticipantRenderViewStreamSize: (RemoteParticipantVideoViewId) -> CGSize?
I wonder if it's necessary to have a separated function to get the videoStreamSize?
Could we just get size from the function `getRemoteParticipantRendererView: (RemoteParticipantVideoViewId) -> (UIView, CGSize)?`
When we return the rendererView, we can just also pass the CGSize of the renderer from the videoStreamCache which is an easy calculation. And this can make code cleaner and easier for read

2022-01-18 06:36 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
> +import AzureCommunicationCalling
We are not going to couple the viewModel with `AzureCommunicationCalling` SDK. Could we remove the import here?

2022-01-18 06:36 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
> +struct ZoomableVideoRenderView: UIViewRepresentable {
Curious about if CallingSDK will support zooming in the video stream view? Or that's need to be done in the UI level by ourself?

2022-01-18 19:03 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
> +struct ZoomableVideoRenderView: UIViewRepresentable {
As far as I know, the `RendererView` from CallingSDK is not capable of supporting user zoom nor panning. We'll need to either check with the SDK team to provide support for that or supporting by ourself.

2022-01-18 19:04 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
> +import AzureCommunicationCalling
yes I think we can use an enum to represent the scaling mode.

2022-01-18 19:06 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
> +    let getRemoteParticipantRenderViewStreamSize: (RemoteParticipantVideoViewId) -> CGSize?
yeah this is a very good point. Actually this was what I had tried with Inderpal as well initially. So far we've found that the size info won't be ready till sometime **after** the `RenderView` has been displayed on the device. This has made me think to create a callback like this, to get a actual size later time, when user starts to zoom the RenderView.

2022-01-18 19:08 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
> +    let getRemoteParticipantRenderViewStreamSize: (RemoteParticipantVideoViewId) -> CGSize?
Alternatively I am checking if we can ask the SDK team to provide the size info for the video so we'd skip creating extra functions to get the size info.

2022-02-01 16:21 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
> +import AzureCommunicationCalling
removed `AzureCommunicationCalling` dependency

2022-02-17 04:34 UTC, waynemo commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellVideoView.swift
> +import AzureCommunicationCalling
Are we able to encapsulate all API calls and types related to the Calling SDK so that they are all within the VideoViewManager? VideoViewManager would only return UIViews so that only it needs to reference AzureCommunicationCalling.

2022-02-17 04:35 UTC, waynemo requested changes

2022-02-17 04:35 UTC, waynemo commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellVideoView.swift
> +import AzureCommunicationCalling
Are we able to encapsulate all API calls and types related to the Calling SDK so that they are all within the VideoViewManager? VideoViewManager would only return UIViews so that only it needs to reference AzureCommunicationCalling.

2022-02-17 21:05 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellVideoView.swift
> +import AzureCommunicationCalling
> Are we able to encapsulate all API calls and types related to the Calling SDK so that they are all within the VideoViewManager? VideoViewManager would only return UIViews so that only it needs to reference AzureCommunicationCalling.

The reason of importing AzureCommunicationCalling into this view is to pass the reference of the VideoStreamRenderer to `ZoomableVideoRenderView` (screenshare) so that the `ZoomableVideoRenderView` can become a delegate of the VideoStreamRenderer (screenshare) and respond to video frame updates. I can try to make the VideoViewManager become a delegate of the VideoStreamRenderer so the views will just have to import 
AzureCommunicationCalling

2022-02-18 00:28 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
> +        let orientationChangeZoomScale = isiPadScreen() ? Constants.minScaleiPad : Constants.minScaleiPhone
yes, the iPad scale needs to be different than iPhone. 

Context: the renderer view SDK calculate the size of the screenshare video based on the iOS hosting view. The size of the screenshare video will determine the quality of the video. The view/device screen, the larger the renderer view size SDK would return, (the better the video quality of the screen share it can have). For iPhone, given the limited physical dimension of the screen, the video quality returned is blurry and that's why the scale in iPhone needs to be different from iPad.

Given the large physical dimension of the device screen, we can keep the scale of iPad at (min 1, max 4).

2022-02-22 20:29 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellVideoView.swift
> +import AzureCommunicationCalling
Instead of having `getRemoteParticipantScreenShareVideoStreamRenderer` and `getRemoteParticipantRendererView` could we combine these two closure by returning `VideoStreamCache`?

2022-02-22 20:29 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/VideoViewManager.swift
> +    func getRemoteParticipantVideoRendererViewSize(_ videoViewId: RemoteParticipantVideoViewId) -> CGSize? {
Does this function being called anywhere?

2022-02-22 20:29 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
> +        func videoStreamRenderer(didFailToStart renderer: VideoStreamRenderer) {
Should we put a log here?

2022-02-22 20:29 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
> +            rendererView.updateRendererViewSize()
Curious about when this function would be called?

2022-02-22 20:29 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
> +    private func getDisplayingVideoStreamType(
Could we combine this function with `getDisplayingVideoStreamId` to some function like 
```
getDisplayingVideoStreamIdAndType(...) -> (Stirng?, VideoStreamInfoModel.MediaStreamType?)
```

2022-02-22 20:29 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellVideoView.swift
> +                                rendererView: self.rendererView).gesture(TapGesture(count: 2).onEnded({}))
`onEnded` is waiting for update in next PR, correct?

2022-02-22 20:29 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellVideoView.swift
> +    let zoomable: Bool
Should zoomable also be the type @Binding through? in case the remote participant update to screenshare from local video stream? Probably change the property to media stream type

2022-02-22 20:29 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellVideoView.swift
> +                            .frame(width: geometry.size.width - 0,
` - 0` here? Could we remove it then

2022-02-23 02:22 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/VideoViewManager.swift
> +    func getRemoteParticipantVideoRendererViewSize(_ videoViewId: RemoteParticipantVideoViewId) -> CGSize? {
I think this was called before the refactor, it is removed now.

2022-02-23 02:25 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellVideoView.swift
> +                                rendererView: self.rendererView).gesture(TapGesture(count: 2).onEnded({}))
yes this is a work around to resolve the double tap / single tap interference. I am going to look into ways to improve in the next PR (another user story)

2022-02-23 02:26 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellVideoView.swift
> +                            .frame(width: geometry.size.width - 0,
yes, I will remove

2022-02-23 02:26 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
> +        func videoStreamRenderer(didFailToStart renderer: VideoStreamRenderer) {
sure

2022-02-23 02:32 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellVideoView.swift
> +import AzureCommunicationCalling
Yes, returning VideoStreamCache would be one way for the `ZoomableVideoRenderView` to be set as the **delegate** of the VideoStreamRenderer. One thing I'd concern is that to set this **delegate** (which is of type `RendererDelegate`), in `ZoomableVideoRenderView`, `ZoomableVideoRenderView` has to import reference to AzureCommunicationCalling. Are we trying to avoid introducing AzureCommunicationCalling references into our view?

To avoid having to refer to `AzureCommunicationCalling` in the Swift UI views,I added a delegate `VideoScreenShareDelegate` which has pretty much same function from the RendererDelegate from SDK, and made the child view become the delegate to the `VideoViewManager`.

2022-02-23 18:22 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
> +    private func getDisplayingVideoStreamType(
yes, updated the code with the suggested changes

2022-02-24 06:55 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/VideoViewManager.swift
> +    func getScreenShareVideoStreamRenderer(_ videoViewId: RemoteParticipantVideoViewId) -> VideoStreamRenderer? {
done

2022-02-24 07:01 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
> +    let videoViewManager: VideoViewManager
I had to use a class instead of a struct here. This `VideoScreenShareDelegate` will be set to `context.coordinator` in the `func makeUIView(context: Context)` in `ZoomableVideoRenderView`, and declaring this `ParticipantRendererViewWithDelegate` as set would require us to change this function to a `mutating` type, which will make the `ZoomableVideoRenderView` not conforming to `UIViewRepresentable` anymore.  
also would it be good to rename this `ParticipantRendererViewWithDelegate` to `ParticipantRendererViewInfo`?

2022-03-02 22:57 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
> +            if state.lifeCycleState.currentStatus == .background {
Do we need an extra check here?
the currentStatus can be either `foreground` or `background` though?
if state.lifeCycleState.currentStatus != .foreground, then state.lifeCycleState.currentStatus should be background

2022-03-02 22:57 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
> +        videoRendererViewInfo.delegate = context.coordinator
Need to remove the line 54 here. Otherwiese I can't run the branch code.

2022-03-02 22:57 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/VideoViewManager.swift
> +    weak var videoManager: VideoViewManager?
Thanks for taking my suggestion to use a struct to wrap the needed properties. 
But if we have to wrap the VideoViewManager inside the struct, I think it makes more sense to directly pass the a protocol all the way down to the `ParticipantGridView`, `ParticipantGridLayoutView`, `ParticipantGridCellVideoView`. Replace the `getRemoteParticipantRendererView` with the protocol, and the `videoViewManager` is the protocol implementation. Reasons are:  

- This can simplify the videoViewManager function and makes the code clean and easy for maintenance. 
- From performance side, reading the properties from closure or from manager shouldn't have difference. I think the original idea is to isolate view from knowing videoViewManager. To achieve the same propose, we can have a protocol, , and the `videoViewManager` is the protocol implementation. like 
```
protocol ParticipantRendererViewManager: AnyObject {
getRemoteParticipantVideoRendererView() -> RendererView
getRemoteParticipantVideoRenderer() -> Render
getRemoteParticipantVideSize() -> CGSize
getRemoteParticipantVideoDelegate() -> Delegate (or a property)
}
```
and pass the protocol object to view layer with `getRemoteParticipantRendererView`

2022-03-02 22:57 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/VideoViewManager.swift
> +                newRenderer.delegate = self
I know it works for now, but what's in future we need to handle multiple delegate from different views? Ideally it's more recommenned to bind the delegate with the view containing the renderer view, because the view is the final consumer from the renderer updates. 
But I think for now, this should be good.

2022-03-02 23:00 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
> +        videoRendererViewInfo.delegate = context.coordinator
yes, I just removed line 54

2022-03-02 23:26 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/VideoViewManager.swift
> +                newRenderer.delegate = self
Agreed. Binding the SDK delegate (RendererDelegate) with the child view would introduce the `AzureCommunicationCalling` reference into the child view as well though. I think the previous approach from this PR had this binding and we removed that to avoid in introducing the `AzureCommunicationCalling` reference into the child view (`ZoomableVideoRenderView`)

2022-03-02 23:40 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
> +            if state.lifeCycleState.currentStatus == .background {
I think the `lifeCycleState.currenStatus` has two values `.foreground` or `.background`. if the `lifeCycleState.currenStatus` is not .foreground then it will go to the else case in the guard where participantGridsViewModel will be updated. What additional check are you referring to @AmyL219?

2022-03-02 23:43 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/VideoViewManager.swift
> +    weak var videoManager: VideoViewManager?
I can try that option. `RendererView` and `Render` are Types from SDK. We'll need references to `AzureCommunicationCalling` in our view that calls the function from the ParticipantRendererViewManager object.  Is that intended?

2022-03-02 23:46 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/VideoViewManager.swift
> +    weak var videoManager: VideoViewManager?
we might to modify the methods from the protocol ParticipantRendererViewManager to only return non SDK types: 
```
protocol ParticipantRendererViewManager: AnyObject {
getRemoteParticipantVideoRendererView() -> UIView?
getRemoteParticipantVideSize() -> CGSize
getRemoteParticipantVideoDelegate() -> a custom delegate, not `RendererDelegate` from SDK  (or a property)
}
```

2022-03-03 07:54 UTC, waynemo submitted a review, later dismissed

2022-03-03 07:54 UTC, waynemo commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
> +    private func getDisplayingVideoStreamIdAndType(_ participantModel: ParticipantInfoModel) ->
This would be more readable if it returned some kind of type instead of a tuple. 

On the Android side, this view model publishes a `VideoViewModel`. Could we do the same, where `videoStreamId` and `videoStreamType` are properties of `VideoViewModel`?

2022-03-03 07:54 UTC, waynemo commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/ParticipantGridViewModel.swift
> +    func update(remoteParticipantsState: RemoteParticipantsState, lifeCycleState: LifeCycleState) {
I don't think it is necessary to pass the `LifeCycleState` as part of the update just so we can pass `isAppInForeground` all the way to the `ZoomableVideoRenderView`.

Instead, we could expose a method on `AppLifeCycleManager` to get the current foreground/background state. `AppLifeCycleManager` can then be injected into `ZoomableVideoRenderView` and called to check the foreground/background state for rendering.

2022-03-03 19:08 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
> +    @Published var videoStreamType: VideoStreamInfoModel.MediaStreamType?
instead of publishing videoStreamId, and videoStreamType, consider publishing a new type that wrap these two attributes. Referred to [ https://github.com/Azure/communication-ui-library-android/blob/develop/beta/azure-communication-ui/azure-communication-ui/src/main/java/com/azure/android/communication/ui/presentation/fragment/calling/participant/grid/ParticipantGridCellViewModel.kt#L48](url)

2022-03-03 19:24 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/ParticipantGridViewModel.swift
> +    func update(remoteParticipantsState: RemoteParticipantsState, lifeCycleState: LifeCycleState) {
to use environment variable that carry the foreground/background info from AppLifeCycleManager

2022-03-04 15:54 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
> +    private func getDisplayingVideoStreamIdAndType(_ participantModel: ParticipantInfoModel) ->
added

2022-03-04 20:41 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
> +            if state.lifeCycleState.currentStatus == .background {
I mean does this work the same?
```
 guard state.lifeCycleState.currentStatus == .foreground else {

participantGridsViewModel.update(remoteParticipantsState: state.remoteParticipantsState,
                                                 lifeCycleState: state.lifeCycleState)
return
}
```

2022-03-04 20:42 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
> +class VideoViewModel {
Should this be a `Struct`?

2022-03-04 20:45 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
> +class VideoViewModel {
https://forums.raywenderlich.com/t/question-about-struct-vs-class/61980

2022-03-04 21:15 UTC, AmyL219 commented
There is a bug that the screensharing view wouldn't be display, please try the reproduce steps:
1. Join a team's call **with the remote participant open his camera**
2. Put the device in **landscape** mode after being admitted
3. Start screen sharing inside the Teams client side
4. You would see the grey view as the screen sharing view
![MicrosoftTeams-image (25)](https://user-images.githubusercontent.com/75647512/156842554-982181ef-82f0-45da-8433-30b9316767d5.png)

2022-03-04 23:09 UTC, JoshuaLai commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
> +            if state.lifeCycleState.currentStatus == .background {
Agree with @AmyL219 I think the `if` is a redundant check and can be removed.

2022-03-04 23:13 UTC, JoshuaLai commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
> +class VideoViewModel {
If we are moving this to a struct(which I think you can do, it doesn't look like you are holding onto state and nothing is mutating) lets make sure to change the properties from `var` to `let`

2022-03-10 19:39 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
> +        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0) {
Could we update to 
```
 DispatchQueue.main.async {
}
```
Since there no usage of delay?

2022-03-10 19:39 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
> +        appState = store.state.lifeCycleState.currentStatus == .foreground ? .foreground : .background
Would this work?
`appState = state.lifeCycleState.currentStatus`

2022-03-10 21:31 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
> +struct VideoViewModel {
sure

2022-03-10 21:55 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
> +        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0) {
for some reason DispatchQueue.main.async would not work. I ended up using the `DispatchQueue.main.asyncAfter` as a workaround

2022-03-10 23:06 UTC, AmyL219 submitted a review, later dismissed
Let's create bug tickets for the remaining issues. Be free the bug to me if helps needed

2022-03-11 00:49 UTC, kevinyulu commented
For the bugs @AmyL219 @palatter relayed, I am going to create new bug ticket.

2022-03-11 01:00 UTC, vhuseinova-msft approved these changes, later dismissed
Added an minor code improvement

2022-03-11 01:00 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
> +        scrollView.zoomScale = isiPadScreen() ? Constants.minScaleiPad : Constants.minScaleiPhone
minimumZoomScale value can be created and reused in scrollView.minimumZoomScale and scrollView.zoomScale

2022-03-11 01:00 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/Grid/Cell/ZoomableVideoRenderView.swift
> +        scrollView.zoomScale = isiPadScreen() ? Constants.minScaleiPad : Constants.minScaleiPhone
Maybe even create it as a private property as it's reused later in updateUIView(_ uiView: UIScrollView, context: Context) and zoomScrollView(basedOn point: CGPoint, scale: CGFloat) and a couple of other places

2022-03-11 01:26 UTC, vhuseinova-msft approved these changes

2022-03-11 04:13 UTC, AmyL219 approved these changes

2022-03-11 17:05 UTC, merged