[Feature][DemoApp] Add XCUITest inside Demo App
Azure/communication-ui-library-ios pull request #42
Opened 2022-02-10 21:50 UTC by AmyL219

## Purpose

* Add AzureCommunicationUIDemoAppUITests  as test target inside AzureCommunicationUIDemoApp
* Add info.plist to configure environment variables inside UI tests ( the `expiredAcsToken` for now, you need to add this variable inside local `EnvConfig.xcconfig` file) 
* Add `XCTestCase` as the base class
* Pod `import SwiftLint` for AzureCommunicationUIDemoAppUITests
* Some basic UI tests setup 

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  See if you can run the local UI test after adding `expiredAcsToken` to your local `EnvConfig.xcconfig` file 

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

2022-02-24 00:25 UTC, vhuseinova-msft requested changes

2022-02-24 17:14 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppUITestsLaunchTests.swift
> +        let attachment = XCTAttachment(screenshot: app.screenshot())
This is a system added file from the UI Tests Example. Haven't updated any code of it yet since take it as a system default test.

2022-02-24 17:31 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppUITests.swift
> +        let app = XCUIApplication()
Yeah, haven't do too much code refactoring work yet since the [User Story 2708066](https://skype.visualstudio.com/SPOOL/_workitems/edit/2708066) is mainly adding the XCUITest. We have other tickets to refactoring these test cases. This is only POC code.
But it's not ideal to do `setup` inside XCUITestBase since we have different requirements for app's launch, like resetting permission status. But update the `function setup` in this file for now.

2022-02-24 22:09 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppUITests.swift
> +        super.setUp()
This code may be a problem in future if tests parallel execution will be enabled

2022-02-24 22:16 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppUITests.swift
> +        let app = XCUIApplication()
> But it's not ideal to do setup inside XCUITestBase since we have different requirements for app's launch, like resetting permission status.

This functionality can be improved by creating a setup func in the same way as we create a sut object for some unit tests (makeSUT func). JFYI, it shouln't be the same as makeSUT func.

2022-02-24 22:23 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppUITestsLaunchTests.swift
> +        let attachment = XCTAttachment(screenshot: app.screenshot())
Sounds good. It would be great to create infrastracture for screenshots, so the code will be reused and an amoung of duplications and merge conflicts will be decreased. Do you want me to create a separate task for this?

2022-02-24 23:13 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppUITestsLaunchTests.swift
> +        let attachment = XCTAttachment(screenshot: app.screenshot())
We do have another spike ticket
[User Story 2714478](https://skype.visualstudio.com/SPOOL/_workitems/edit/2714478): [iOS] Spike taking screenshot for local testing and CI pipeline

2022-02-24 23:20 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppUITests.swift
> +        let app = XCUIApplication()
Uhh, I take the test code from[ Microsoft Outlook UI Test](https://office.visualstudio.com/Outlook%20Mobile/_git/ios-app-center-sdk?path=/Sasquatch/SasquatchUITests/AnalyticsUITests.swift&_a=contents&version=GBmaster) code as an example for setup. 
But I am not quite sure what's the setup func you are talking. Could you paste a link of code as a reference? 

But generally I think using `func setup` should be good enough for this [User Story 2708066](https://skype.visualstudio.com/SPOOL/_workitems/edit/2708066). We can refactoring the test code when implement the test cases tickets.

2022-02-24 23:24 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppUITests.swift
> +        super.setUp()
Uh, curious about why would this become a problem when execute parallel tests

2022-02-24 23:39 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppUITests.swift
> +        super.setUp()
you're right, the setup method is called once before the tests are started as said in session 403, WWDC2018

2022-02-24 23:47 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/AzureCommunicationUIDemoAppUITests.swift
> +        let app = XCUIApplication()
I think it would be a good idea to follow the same pattern in all tests for the app. As for now, we have different patterns: in one clasess we use makeSUT functions and in others - ovverriding setUp func. Added this question for a common discussion.

Resolving this conversation as the change can be added later

2022-02-24 23:48 UTC, vhuseinova-msft submitted a review, later dismissed

2022-03-01 22:22 UTC, JoshuaLai commented on AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/Utilities/XCUITestBase.swift
> +    override func tearDownWithError() throws {
I don't think this function is being used at all for anything so it can be removed.

2022-03-01 22:32 UTC, JoshuaLai commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarView.swift
> +            .accessibility(identifier: "AzureCommunicationUI.CallingView.ControlButton.HangUp")
@palatter just double checking this aligns with the naming convention for accessibility identifiers.

2022-03-01 22:33 UTC, JoshuaLai commented
Just had some quick follow up questions

2022-03-02 22:16 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/Utilities/XCUITestBase.swift
> +    func testExample() throws {
Removed

2022-03-02 22:17 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUIDemoAppUITests/Utilities/XCUITestBase.swift
> +    override func tearDownWithError() throws {
Yeah, Removed

2022-03-02 22:17 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarView.swift
> +            .accessibility(identifier: "AzureCommunicationUI.CallingView.ControlButton.HangUp")
Will sync with Patrick after he is back

2022-03-02 22:20 UTC, JoshuaLai commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarView.swift
> +            .accessibility(identifier: "AzureCommunicationUI.CallingView.ControlButton.HangUp")
Sounds good. We can always merge this in first. Lets create a follow up task to track this.

2022-03-02 22:20 UTC, JoshuaLai approved these changes, later dismissed

2022-03-03 17:32 UTC, vhuseinova-msft approved these changes

2022-03-03 17:59 UTC, JoshuaLai approved these changes

2022-03-03 18:00 UTC, merged