[Feature] Added e2e calling sdk wrapper mock test for calls
Azure/communication-ui-library-ios pull request #424
Opened 2022-11-02 22:27 UTC by kevinyulu

## Purpose

* Added e2e calling sdk wrapper mock test for calls
* Added a new debugger screen that simulates the passive calling state changes (e.g. call on hold, call resume, transcription, recording, etc)

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
run ui test testJoinCallEndCallWithMockCallCallingSDKWrapperHandler()
```

## What to Check
Verify that the following are valid
* make sure the uitest passes 100%

## Other Information

2022-11-23 16:32 UTC, palatter commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_LSApplicationCategoryType = "";
What is this used for?

2022-11-23 16:33 UTC, palatter commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/CallingSDKWrapperInTest.swift
> +            throw CallCompositeInternalError.callEndFailed
To be consistent can we add a logger message here?

2022-11-23 17:44 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/CallingSDKWrapperInTest.swift
> +        // todo: will work on this in the next task
we are descoping video steam for now, I will remove the comment and the other todo about video below

2022-11-25 17:56 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_LSApplicationCategoryType = "";
This might be accidentally introduced with I edited the scheme and info plist. I will remove

2022-11-29 19:44 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_LSApplicationCategoryType = "";
Is it needed?

2022-11-29 19:48 UTC, vhuseinova-msft submitted a review, later dismissed

2022-11-29 22:56 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_LSApplicationCategoryType = "";
this is introduced by accident I will remove

2022-11-30 21:18 UTC, vhuseinova-msft requested changes
@kevinyulu  Could you please review failed tests?

2022-12-01 21:47 UTC, vhuseinova-msft approved these changes, later dismissed

2022-12-05 16:33 UTC, emlynmac requested changes
It looks like there are now some test classes that are being constructed as part of the library.
We should not be shipping test code as part of the library; they should be part of the demo application.

2022-12-05 18:35 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/UITestSettingsView.swift
> +                        viewModel.action(.callingAction(.holdRequested))
The point of mocking the calling SDK is so the tests can be triggered from there; not from sending the action into redux.

2022-12-05 23:25 UTC, kevinyulu commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
> +                                     isUITestEnabled: self.customCallingSdkWrapper != nil)
This was to toggle the visibility of the "Debugger" button and show the button only when the uitest is taking place

2022-12-06 18:07 UTC, kevinyulu commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/UITestSettingsView.swift
> +struct UITestSettingsView: View {
I tried adding a overlay window from the demo app and connect the action to use mock sdk. The issue I see so far is that XCUITest has issue finding the element via accessibilityID and apply the tap action. I see similar issue in app center that app is not able to find element in the current UITest settings view: https://appcenter.ms/orgs/Azure-Communication-Services/apps/Azure-Communication-Services-Call-UI-Library-Sample-iOS-Internal/test/runs/fc72d341-849c-4026-9105-776241f06e2e/0-0-0/b741526b-11ac-4594-80e1-95deec50e79c/logs

2022-12-13 16:35 UTC, emlynmac reviewed
Some tidy up to do before we can land this PR.

2022-12-13 16:35 UTC, emlynmac commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/CallingSDKWrapperInTest.swift
> +//
Does this file need to be removed from the commit?

2022-12-13 16:35 UTC, emlynmac commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/FloatingUITestWindow.swift
> +class FloatingUITestWindow: UIWindow {
Let's make sure this window is only visible when the mock calling SDK is actively enabled in the configuration

2022-12-14 20:30 UTC, emlynmac commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/EntryViewController.swift
> +            window = FloatingUITestWindow(windowScene: windowScenes)
Should this start as hidden and be made visible only when the mock calling SDK is enabled?

2022-12-14 22:42 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/EntryViewController.swift
> +            window = FloatingUITestWindow(windowScene: windowScenes)
done

2022-12-14 22:42 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/FloatingUITestWindow.swift
> +class FloatingUITestWindow: UIWindow {
done

2022-12-14 23:32 UTC, kevinyulu commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/Utilities/XCUITestBase.swift
> +    var isOn: Bool? {
defaulted to false

2022-12-15 18:23 UTC, emlynmac commented
This has been superseded by https://github.com/Azure/communication-ui-library-ios/pull/543

2022-12-15 18:23 UTC, closed without merging