[Refactor] Refactor and renaming of public api for chat
Azure/communication-ui-library-ios pull request #458
Opened 2022-11-18 18:20 UTC by jimchou-dev

## Purpose

* Refactor public api for chat
* Rename composite to adapter for chat
* Refactor demo app to have separate UIKit and SwiftUI views for chat

## Does this introduce a breaking change?

- [ ] Yes
- [ x ] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ x ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull request checklist

This PR has considered:
- [ ] Color Theming
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] View Data Injection
- [ ] Demo App UI/UX update

## How to Test

* Open...
* Click on...

## What to Check

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

## Other Information

2022-11-18 19:42 UTC, JoshuaLai commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
> +        self.chatConfiguration = ChatConfiguration(
I wonder if we just make `ChatConfiguration` public and instead of having all these arguments just have developers pass in this object

2022-11-18 19:43 UTC, JoshuaLai commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
> +        compositeManager?.start()
Nitpick: I think this can just be moved into helper that both connect methods can call

2022-11-18 19:44 UTC, JoshuaLai commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
> +                        completionHandler: ((Result<Void, ChatCompositeError>) -> Void)? = nil) {
Is this completion just being called atm?

2022-11-18 19:47 UTC, jimchou-dev commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
> +                        completionHandler: ((Result<Void, ChatCompositeError>) -> Void)? = nil) {
Yes the SwiftUI demo app is using the completionHandler to print out in console

2022-11-18 19:48 UTC, jimchou-dev commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
> +        compositeManager?.start()
Made the async method is calling the sync method

2022-11-18 19:58 UTC, JoshuaLai commented
I think this is a fine first draft. But we will need to create tasks to fill in the missing pieces, code clean up and perform memory tests as well.

2022-11-18 20:00 UTC, JoshuaLai approved these changes, later dismissed

2022-11-18 20:31 UTC, emlynmac requested changes, later dismissed
Looks like a good start!

2022-11-18 20:31 UTC, emlynmac commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatSwiftUIDemoView.swift
> +        print("Error - \(error.code): \(error.error?.localizedDescription ?? error.localizedDescription)")
I guess this needs conversion to a `Logger.error()` call?

2022-11-18 20:31 UTC, emlynmac commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatUIKitDemoViewController.swift
> +class ChatUIKitDemoViewController: UIViewController {
`ChatViewController` should be sufficient here?

2022-11-18 20:31 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
> +                        completionHandler: ((Result<Void, ChatCompositeError>) -> Void)? = nil) {
The completion handler should not be allowed to be nil. 
Given that connect requires a callback to complete or fail, we must force consumers of this API to implement this method.

2022-11-18 20:31 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
> +        connect(threadId: threadId, completionHandler: nil)
This needs to be implemented as a wrapper with a continuation.

2022-11-18 20:31 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/ChatConfiguration.swift
> +    var chatThreadId: String
Why does the thread ID need to be a var here?
Perhaps it does not belong in the ChatConfiguration, if it cannot be determined at the same point in the connection set-up?

2022-11-18 20:31 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/ChatCompositeView.swift
> +        self.router = self.chatAdapter.dependencyContainer!.resolve()
Forced-unwrapped values must not be used; our linter should be catching this.

2022-11-18 21:43 UTC, jimchou-dev commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/ChatSwiftUIDemoView.swift
> +        print("Error - \(error.code): \(error.error?.localizedDescription ?? error.localizedDescription)")
The demo app doesn't have logger, we can refactor the demo app to have its logger in the future but will skip that in this PR.

2022-11-18 21:46 UTC, jimchou-dev commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatCompositeOptions/ChatConfiguration.swift
> +    var chatThreadId: String
Josh made a similar comment on ChatConfiguration, I'll create a task (ADO 3061412) to refactor this out, I'll create a task for it to refactor it out.

2022-11-18 21:48 UTC, jimchou-dev commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/ChatAdapter.swift
> +        self.chatConfiguration = ChatConfiguration(
I think from previous discussion with calling there were different terms for options/config/settings etc... and we decide to only be using Options, but we got rid of RemoteOptions, so doesnt that mean we would be re-introducing it but without the threadId/locator?

Also the reason we have chatConfiguration internally is it's collectively passing information from redux layer to service layer in a simple call, but since it does not contain threadId anymore. I'll create a task (ADO 3061412) to refactor this out.

2022-11-21 19:06 UTC, JoshuaLai approved these changes

2022-11-21 21:24 UTC, merged