[Refactor] Update FluentUI version to 0.3.9
Azure/communication-ui-library-ios pull request #49
Opened 2022-02-16 19:54 UTC by cheukchuen

## Purpose

* Fixes inconsistent display when dragging an opened participants list

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What to Check
Verify that the following are valid
* Check that participants list content is being displayed consistently when dragging the drawer while opened
* Check that FluentUI controls (Avatar, BottomSheet, Button, PopupMenu) function the same

2022-02-16 19:59 UTC, waynemo requested changes, later dismissed
@cheukchuen please update CHANGELOG to indicate the dependency update and bug fixed.

2022-02-16 20:28 UTC, kevinyulu approved these changes

2022-02-16 23:35 UTC, AmyL219 approved these changes

2022-02-17 17:13 UTC, jimchou-dev approved these changes

2022-02-17 18:09 UTC, merged