[Feature] Localization public api interface and configure locale
Azure/communication-ui-library-ios pull request #54
Opened 2022-02-25 18:12 UTC by jimchou-dev

## Purpose

* Public facing api for Localization
  * Initialize LocalizationConfiguration with customStrings
  * Initialize LocalizationConfiguration with locale and custom localizable.strings file name
  * Get default supported languages
  * Get predefined localization strings for support language, if unsupported language is provided will return empty dictionary * Remove locale in compliance banner URL, will redirect to appropriate language based on user's browser language

## Does this introduce a breaking change?

```
[ ] Yes
[ x ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What to Check
Verify that the following are valid
* Test when providing a unsupported language in LocalizationConfiguration will log warning message
* Can use static method to get supported languages
* Can use static method to get predefined key-value strings for supported languages
* Switch to a different language on device and test Teams call with recording/transcription, and click on `Learn more` or `Privacy Policy` will open website to system/browser language

## Other Information

2022-02-25 18:34 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/CallCompositeOptions.swift
> +    var localizationConfiguration: LocalizationConfiguration?
Could we make this property as private(set) (as it's initialized in init function) or a user should be able to update it later too?

2022-02-25 19:46 UTC, vhuseinova-msft commented
Tested, LGTM

2022-02-25 19:46 UTC, vhuseinova-msft approved these changes

2022-02-25 21:06 UTC, jimchou-dev commented on AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/CallCompositeOptions.swift
> +    var localizationConfiguration: LocalizationConfiguration?
Make sense, will be consistent and also change themeConfiguration to private(set)

2022-03-03 21:05 UTC, waynemo requested changes

2022-03-03 21:05 UTC, waynemo commented on AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/CallCompositeOptions.swift
> +    public init(themeConfiguration: ThemeConfiguration? = nil,
Should we have separate initializers that handle ThemeConfiguration and LocalizationConfiguration individually?

2022-03-03 21:05 UTC, waynemo commented on AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/LocalizationConfiguration.swift
> +                locale: String,
Why would we need `locale` passed in here? With customStrings, wouldn't it just use those regardless of the locale?

2022-03-03 22:41 UTC, jimchou-dev commented on AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/LocalizationConfiguration.swift
> +                locale: String,
Android team discussion suggests we should allow Contoso to provide a fallback locale, if they did not call `getLocaleStringDict()` and set it as the customStrings, if they just created a dictionary to override a few keys to in the customString, it should allow them to have a fallback language instead of always falling back to english (if unsupported locale is provided and key is not provided in customStrings dict, English strings will be used as default).

2022-03-03 22:41 UTC, jimchou-dev commented on AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/CallCompositeOptions.swift
> +    public init(themeConfiguration: ThemeConfiguration? = nil,
Having default parameter allow Contoso to treat it as separate initializer if they only choose to do one or the other or both. Azure review board for iOS said this is okay, otherwise in the future if we have more configurable parameters, there will be too many initializers to manage.

2022-03-04 19:56 UTC, JoshuaLai commented on AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/LocalizationConfiguration.swift
> +    /// - Parameter locale: Name of the language locale.
I worry "Name" might be a little confusing. Developers might accidentally put in the "french" as a string. And since it is just a string there is a lot of room of interpretation and confusion
```suggestion
    /// - Parameter locale: String representing the locale code (ie. en, en_CA, fr, fr_FR)
```

2022-03-04 20:05 UTC, JoshuaLai commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/Banner/BannerInfoType.swift
> +            return "https://privacy.microsoft.com/privacystatement#mainnoticetoendusersmodule"
Interesting. How do we know to go to the proper language if we don't pass in the locale code?

2022-03-04 20:07 UTC, JoshuaLai approved these changes
lgtm just a quick suggestion about your comment block and a small question about the privacy url

2022-03-04 20:31 UTC, jimchou-dev commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewComponent/Banner/BannerInfoType.swift
> +            return "https://privacy.microsoft.com/privacystatement#mainnoticetoendusersmodule"
Its the solution suggested by localization team, without locale, it will redirect based on the browser/system language

2022-03-04 20:32 UTC, jimchou-dev commented on AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/LocalizationConfiguration.swift
> +    /// - Parameter locale: Name of the language locale.
The comment is not finalized, still need to sync with Android, will have a separate PR to correct them. Good suggestion locale code is probably better =)

2022-03-07 21:36 UTC, jimchou-dev commented on AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/CallCompositeOptions.swift
> +    public init(themeConfiguration: ThemeConfiguration? = nil,
Travis said having initializer with optional value that is default `nil` is okay. Also suggested to change CallComposite initializer to have `withOptions` optional with default nil value

2022-03-07 22:16 UTC, JoshuaLai commented on AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/LocalizationConfiguration.swift
> -    public static func getLocaleStringDict(locale: String) -> [String: String] {
Was there a reason for why we wanted this removed?

2022-03-07 22:22 UTC, jimchou-dev commented on AzureCommunicationUI/AzureCommunicationUI/CallCompositeOptions/LocalizationConfiguration.swift
> -    public static func getLocaleStringDict(locale: String) -> [String: String] {
Android is having some issue converting strings.xml to hashMap, so to keep API consistent across platform, we won't expose this function as part of the API

2022-03-07 22:31 UTC, merged