[Draft][Bugfix] Fix scrolling and fetch issues.
Azure/communication-ui-library-ios pull request #554
Opened 2022-12-20 21:04 UTC by palatter

## Purpose

* ...

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull request checklist

This PR has considered:
- [ ] Color Theming
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] View Data Injection
- [ ] Demo App UI/UX update

## How to Test

* Open...
* Click on...

## What to Check

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

## Other Information

2022-12-21 23:52 UTC, kevinyulu commented
I noticed that the loading spinner appears at the bottom of the chat view, everything else looks good.

2022-12-28 17:14 UTC, palatter commented
> I noticed that the loading spinner appears at the bottom of the chat view, everything else looks good. ![Simulator Screen Shot - iPhone 13 Pro - 2022-12-21 at 15 52 26](https://user-images.githubusercontent.com/90668345/209025356-48519713-99e5-4872-93a5-c0db2c090bdb.png)

Fixed.

2022-12-28 22:00 UTC, JoshuaLai commented
Tested and seems to be working as expected for small chat and long chat. Known issue related with the spinner now disappearing at the top of the chat if we have fetched all messages. There also seem to be some swift lint issues in the branch that need to be resolved.

2022-12-29 21:35 UTC, JoshuaLai submitted a review, later dismissed

2022-12-29 23:33 UTC, Leah-Xia-Microsoft commented
Seems like when it reaches the first message of the thread, the fetch activity indicator doesn't disappear.
https://user-images.githubusercontent.com/107075081/210020762-c583d72a-b97a-4872-93be-aa2e8b31dc6f.MP4

2022-12-29 23:44 UTC, Leah-Xia-Microsoft requested changes
2 edge cases for fetch. Everything else looks awesome.

2022-12-29 23:47 UTC, Leah-Xia-Microsoft commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
> +            print("SCROLL: Fetch Messages")
Do we intend to keep this print?

2022-12-30 17:15 UTC, palatter commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Presentation/SwiftUI/Chat/ChatViewComponents/MessageListViewModel.swift
> +            print("SCROLL: Fetch Messages")
Oh good catch! I think there are a couple of those. I'll remove.

2022-12-30 18:29 UTC, palatter commented
> Seems like when it reaches the first message of the thread, the fetch activity indicator doesn't disappear. https://user-images.githubusercontent.com/107075081/210020762-c583d72a-b97a-4872-93be-aa2e8b31dc6f.MP4
> 
> Also, when leaving the thread and reenter, fetch indicator doesn't disappear either. For this one, it might be related to
> 
> ```
>     func onDisappear() {
>         self.hasFetchedInitialMessages = false
>         didEndScrollingTimer?.invalidate()
>     }
> ```
> 
>  RPReplay_Final1672356930.MP4

Fixed the issue where the activity indicator was staying on screen when returning.

For the other issue, I want to discuss the best approach with Jim, as it will involve determining if we have gotten all messages in the wrapper/service level. So I'll leave that for another PR.

2022-12-30 18:52 UTC, JoshuaLai approved these changes, later dismissed

2022-12-30 20:16 UTC, Leah-Xia-Microsoft approved these changes
The send read receipt feature is affected but I'll fix it in another PR

2022-12-30 20:22 UTC, JoshuaLai approved these changes

2022-12-30 20:22 UTC, merged