[Feature][Refactor] Migrate AppCenter test pipeline to YAML
Azure/communication-ui-library-ios pull request #555
Opened 2022-12-20 23:00 UTC by emlynmac

## Purpose
Our AppCenter automated UI tests are quite complex in setup, execution and scheduling.
Migrating all the logic to YAML templates has clarified the pipeline and enabled clearer maintenance moving forward.

The nightly pipeline now checks every two hours if it should execute. 
If it finds a configured device set, it runs the AppCenter tests with that device set. 
This is configured in the set-appcenter-devices.yml file

The 3am nightly task still runs for basic UI tests and release mode.

I'll be reviewing the logic in the New Year with a tech talk.

## Does this introduce a breaking change?
- [ ] Yes
- [x] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

2022-12-20 23:07 UTC, emlynmac commented on eng/pipelines/jobs/templates/set-appcenter-devices.yml
> +      case $DAY_OF_WEEK in
When reviewing, please check this logic against the OneNote schedule [here](https://microsoft.sharepoint-df.com/teams/ACSMobileUI/_layouts/OneNote.aspx?id=%2Fteams%2FACSMobileUI%2FSiteAssets%2FACS%20Mobile%20UI%20Notebook&wd=target%28Quality.one%7C8AC059AD-8D39-4D99-8FFC-CADFA2D68652%2FCall%20Composite%20XCUITest%20App%20Center%20Pipeline%20%28ESRP%20enabled%5C%29%7C9ACD131C-1C8B-744B-8A3C-80F9E01970DC%2F%29)

2022-12-22 17:54 UTC, JoshuaLai approved these changes

2022-12-22 19:00 UTC, vhuseinova-msft approved these changes

2022-12-22 19:02 UTC, Leah-Xia-Microsoft approved these changes

2022-12-22 19:08 UTC, palatter requested changes
Looks good

2022-12-22 19:08 UTC, palatter approved these changes

2022-12-22 19:15 UTC, merged