[Doc] Updated Chat README
Azure/communication-ui-library-ios pull request #566
Opened 2023-01-03 18:50 UTC by jpeng-ms

## Purpose

* ...

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull request checklist

This PR has considered:
- [ ] Color Theming
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] View Data Injection
- [ ] Demo App UI/UX update

## How to Test

* Open...
* Click on...

## What to Check

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

## Other Information

2023-01-03 19:01 UTC, vhuseinova-msft approved these changes, later dismissed

2023-01-03 19:09 UTC, JoshuaLai commented
Can we also update the actual pod spec in the Chat directory as well. There is a version declared in there

2023-01-03 19:17 UTC, palatter submitted a review, later dismissed
Looks good.

2023-01-03 19:43 UTC, JoshuaLai requested changes
Please also update the podspec version

2023-01-03 20:05 UTC, jpeng-ms commented
> Please also update the podspec version



> Please also update the podspec version

updated

2023-01-03 21:11 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.podspec
> +  spec.source               = { :git => 'https://github.com/Azure/communication-ui-library-ios.git', :tag => 'AzureCommunicationUIChat_1.0.0-beta.1' }
I don't see this tag in the repository yet.

2023-01-03 21:16 UTC, jpeng-ms commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.podspec
> +  spec.source               = { :git => 'https://github.com/Azure/communication-ui-library-ios.git', :tag => 'AzureCommunicationUIChat_1.0.0-beta.1' }
that's right, it would be created when we have a release cut if everything is good with bug bash

2023-01-03 21:37 UTC, Leah-Xia-Microsoft approved these changes, later dismissed

2023-01-04 18:40 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.podspec
> +  spec.source               = { :git => 'https://github.com/Azure/communication-ui-library-ios.git', :tag => 'AzureCommunicationUIChat_1.0.0-beta.1' }
So maybe this should be merged when we have the tag created.

2023-01-04 19:25 UTC, jpeng-ms commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.podspec
> +  spec.source               = { :git => 'https://github.com/Azure/communication-ui-library-ios.git', :tag => 'AzureCommunicationUIChat_1.0.0-beta.1' }
why would it be? this just documentation change, unless we plan to name the tag differently, I don't see why it shouldn't be merged?

2023-01-04 19:42 UTC, JoshuaLai approved these changes, later dismissed

2023-01-04 19:56 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.podspec
> +  spec.source               = { :git => 'https://github.com/Azure/communication-ui-library-ios.git', :tag => 'AzureCommunicationUIChat_1.0.0-beta.1' }
This is not a document change; it is the podspec which when published defines the tag to get the chat library source from.
This should be updated with the release branch / tag when we actually release it and not before.

2023-01-04 20:14 UTC, jpeng-ms commented on AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.podspec
> +  spec.source               = { :git => 'https://github.com/Azure/communication-ui-library-ios.git', :tag => 'AzureCommunicationUIChat_1.0.0-beta.1' }
thanks, I reverted it back to develop branch

2023-01-04 20:21 UTC, emlynmac approved these changes

2023-01-04 21:04 UTC, vhuseinova-msft approved these changes

2023-01-04 21:21 UTC, jimchou-dev commented
Should this PR also include updating the `UILibrarySemVersion` in Info.plist?

2023-01-04 21:22 UTC, merged

2023-01-04 21:22 UTC, jpeng-ms commented
> Should this PR also include updating the `UILibrarySemVersion` in Info.plist?

let's do it when we update the pod spec