[Refactor] Common code extraction
Azure/communication-ui-library-ios pull request #602
Opened 2023-01-17 23:51 UTC by emlynmac

## Purpose
Clean up of all the common code into the correct places and removal of public LocalizationOptions from the common module

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

2023-01-18 16:21 UTC, palatter commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/State/AppLifeCycleState.swift
> +
Are we ok with having this swiftUI import in the redux state?

2023-01-18 17:33 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/State/AppLifeCycleState.swift
> +
In order to extend EnvironmentKey, we have to.

2023-01-18 18:09 UTC, waynemo requested changes, later dismissed

2023-01-18 18:09 UTC, waynemo commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/State/AppLifeCycleState.swift
> +
Are we using the extended EnvironmentKey in the redux state? Could we have a separate mapping instead and keep the redux state agnostic of the UI?

2023-01-19 00:05 UTC, Leah-Xia-Microsoft approved these changes, later dismissed

2023-01-19 17:16 UTC, palatter approved these changes, later dismissed
Looks good.

2023-01-19 18:34 UTC, vhuseinova-msft approved these changes

2023-01-19 18:39 UTC, jpeng-ms approved these changes

2023-01-19 18:57 UTC, jimchou-dev approved these changes
LGTM

2023-01-19 21:18 UTC, merged