[Feature][Calling][CSS] Call history
Azure/communication-ui-library-ios pull request #610
Opened 2023-01-27 17:21 UTC by pavelprystinka

## Purpose

* Call history

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull request checklist

This PR has considered:
- [ ] Color Theming
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] View Data Injection
- [ ] Demo App UI/UX update

## How to Test

* Open...
* Click on...

## What to Check

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

## Other Information

2023-01-31 03:00 UTC, grigoryk commented
@pavelprystinka can you please check how much of my feeback on https://github.com/Azure/communication-ui-library-android/pull/710 applies here?

2023-02-07 23:43 UTC, emlynmac requested changes
We need to preserve the public interface.

2023-02-07 23:43 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/DebugInfo.swift
> +    public let callHistoryRecords: [CallHistoryRecord]
This is an API breaking change.
It also requires CallHistoryRecord to be made public; why do we need to have this change?

2023-02-07 23:43 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +    private let storageKey: String = "com.azure.android.communication.ui.calling.CallHistory"
Not sure why we have an android reference here?

2023-02-07 23:43 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +        if let data = UserDefaults.standard.data(forKey: storageKey) {
Need to make sure the userDefaults object can be passed into the class, for the purpose of controlling testing.

2023-02-07 23:43 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +protocol CallHistoryRepositoryProtocol {
We probably don't need a protocol here

2023-02-07 23:43 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +            } catch { }
Probably want to do something in the catch block

2023-02-07 23:43 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/DebugInfoManager.swift
> +        self.callHistoryRepository = callHistoryRepository
The previous version of the function stored the local events as they came in.
The overall architecture I believe was to keep the manager looking after the non-redux side.
We probably should keep the manager object responsible for serializing and grabbing objects from the backing store, for simplicity.

2023-02-07 23:43 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallHistoryService.swift
> +protocol CallHistoryServiceProtocol {
No need for an empty protocol

2023-02-07 23:43 UTC, emlynmac commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
> +            let callComposite = CallComposite()
There are a lot of shared (between UIKit and SwiftUI implementation) objects here. 
Every time this view is re-rendered, each of these will be created.
Let's move the view logic out into a view model, so that it can be shared between both and keep the complexity manageable.

2023-02-07 23:43 UTC, emlynmac commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
> +        let callComposite = CallComposite()
This should be in a shared view model component, used by both UI toolkits.

2023-02-07 23:43 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +                return try decoder.decode([Date: [String]].self, from: data)
Why not use CallHistoryRecord and make it Codable?

2023-02-07 23:43 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallHistoryService.swift
> +class CallHistoryService: CallHistoryServiceProtocol {
Can this functionality exist in the manager class?

2023-02-08 05:59 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/DebugInfo.swift
> +    public let callHistoryRecords: [CallHistoryRecord]
This is a change comparing to previous beta. It is approved by ARB.

2023-02-08 06:04 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +protocol CallHistoryRepositoryProtocol {
Will it be useful in unit tests? If not, will remove.

2023-02-08 06:05 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +    private let storageKey: String = "com.azure.android.communication.ui.calling.CallHistory"
Typo, fixed.

2023-02-08 06:11 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +                return try decoder.decode([Date: [String]].self, from: data)
CallHistoryRecord is part of the public interface. Not sure if ARB will like it.

2023-02-08 06:13 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +        if let data = UserDefaults.standard.data(forKey: storageKey) {
Good idea, moved to init.

2023-02-08 06:16 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/DebugInfoManager.swift
> +        self.callHistoryRepository = callHistoryRepository
As this functionality is available for Contoso by only constructing CallComposite and calling method to get diagnosticsInfo, store does not exist yet, so I separated it in two classes. Plus there is extra limitation on Android with context (another reason to have separate service and manager), so decided to follow same architecture here.

2023-02-08 07:14 UTC, pavelprystinka commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
> +            let callComposite = CallComposite()
That was intention to have a new CallComposite (not initialized with options) instance to return a call history

2023-02-08 18:30 UTC, emlynmac commented
It would be preferable to move the persistence of the call IDs into the lower-level Calling SDK, so that all consumers of that library will benefit.
Have we considered this approach?

2023-02-08 18:31 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +protocol CallHistoryRepositoryProtocol {
Protocols are generally used when there are multiple implementations for a set of functionality.
Unit testing should be possible by passing in dependencies to the object directly.

2023-02-09 18:06 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
> +    @State var callHistoryTitle: String = ""
It would be nice to create a ViewModel for CallingDemoView to move `callHistoryTitle` and `callHistoryMessage` there as properties (as it's not very useful to have them as `State`)

2023-02-09 18:09 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
> +            let callComposite = CallComposite()
Also, it's not be a good idea to create a new `CallComposite` object for showing the history

2023-02-09 18:13 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
> +                var formatter = DateFormatter()
It would be better to have a separate property for `DateFormatter` instead of creating a new object for a button tap. But in this case, the DateFormatter should be a property of ViewModel.

2023-02-09 18:17 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
> +                lastHistoryRecord.callIds.forEach { callId in
minor suggestion: [joined(separator:) ](https://developer.apple.com/documentation/swift/array/joined(separator:)-7uber)func can be used instead

2023-02-09 18:19 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
> +        print("::::CallingDemoView debug info \(callId)")
Should we print the last `callHistoryRecords` here instead?

2023-02-09 18:22 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
> +//        showCallHistoryButton.setTitleColor(UIColor.white, for: .normal)
Is it still needed?

2023-02-09 18:23 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
> +        showCallHistoryButton.layer.cornerRadius = 8
It looks like a lot of code is reused for buttons creation, it may be a good idea to create a separate func with reused code

2023-02-09 18:33 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +                existingCall.append(callId)
Should we use an encrypted value for `callId`?
https://developer.apple.com/documentation/applearchive/encrypting_and_decrypting_a_string

2023-02-09 18:35 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +                return try decoder.decode([Date: [String]].self, from: data)
We probably can use internal extension for `CallHistoryRecord` implementing `Codable` in this case

2023-02-23 17:27 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewModel.swift
> +class CallingDemoViewModel: ObservableObject {
`CallComposite` should be property of `CallingDemoViewModel` instead of View or ViewController

2023-02-23 17:29 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/EntryViewController.swift
> +    private var callingViewModel = CallingDemoViewModel()
it looks like `callingViewModel` isn't changed anywhere so it can be a constant instead of variable

2023-02-23 20:26 UTC, pavelprystinka commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewModel.swift
> +class CallingDemoViewModel: ObservableObject {
That will not be enough. There is already lots of duplicate code between View and ViewController. Initialization with/without mock SDK, events subscription, launch.
Will be done separately from this feature.

2023-02-27 23:36 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Service/CallHistoryRepositoryTests.swift
> +        XCTAssertTrue(firstCall.callIds.contains(callId2))
Minor: Lines 40-42 can be changed to
`XCTAssertEqual(firstCall.callIds, [callId1, callId2])`

2023-02-27 23:39 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +        self.userDefaults = userDefaults
Should we add data clean up here (for the data that are older than 31 day)?

2023-02-27 23:40 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Service/CallHistoryServiceTests.swift
> +        callHistoryRepository = nil
`storeFactory` isn't set to nil. It shouldn't be a critical issue but it would be nice to be consistent with `setUp`

2023-02-27 23:56 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Service/CallHistoryServiceTests.swift
> +        Thread.sleep(forTimeInterval: 5)
Could you please use expectations and closures instead of `sleep` func?
https://developer.apple.com/documentation/xctest/asynchronous_tests_and_expectations

2023-03-01 01:08 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +        self.userDefaults = userDefaults
I'm not sure it good to do such work while initialization phase. We do clean on insert, which is called on every call id change. I've updated logic so when getAll is called old records are also filtered out.

2023-03-01 01:10 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +                existingCall.append(callId)
Privacy team did not consider this as any private data.

2023-03-01 01:17 UTC, pavelprystinka commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
> +            let callComposite = CallComposite()
It is intentionally to tests that new instance of CallComposite (not launched) can retrieve call history.

2023-03-06 21:39 UTC, emlynmac commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
> +    @State var callHistoryMessage: String = ""
Why is this @State?

2023-03-06 21:39 UTC, emlynmac commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
> +            callHistoryMessage += "Call Ids:\n"
This is duplicated in the SwiftUI side; move to the view model to implement logic once?

2023-03-06 21:39 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/UserDefaultsStorage.swift
> +extension UserDefaults: UserDefaultsStorageProtocol {}
Empty implementation definition.

2023-03-06 21:39 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/UserDefaultsStorage.swift
> +    func set(_ value: Any?, forKey key: String)
Any is too broad; better to provide specific set methods for supported types.

2023-03-06 22:02 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/UserDefaultsStorage.swift
> +    func set(_ value: Any?, forKey key: String)
This is how UserDefaults are implemented:
    open func set(_ value: Any?, forKey defaultName: String)

2023-03-06 22:02 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/UserDefaultsStorage.swift
> +extension UserDefaults: UserDefaultsStorageProtocol {}
It's to make UserDefaults also implementing a protocol

2023-03-06 22:02 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +    private let callHistoryDispatchQueue = DispatchQueue(label: "CallHistoryDispatchQueue")
This is the way I found on one of the Apple's articles.

2023-03-06 22:02 UTC, pavelprystinka commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
>          let startButtonHSpacer1 = UIView()
Implemented it on consistency with other buttons

2023-03-06 22:02 UTC, pavelprystinka commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
> +            callHistoryMessage += "Call Ids:\n"
This is a UI logic, not a viewModel's

2023-03-06 22:02 UTC, pavelprystinka commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
> +    @State var callHistoryMessage: String = ""
It is required for alert on the View

2023-03-06 22:02 UTC, pavelprystinka commented on eng/pipelines/nightly.yml
> -      name: vsts-mac-1301-xcode-141
If I need to make this branch run on that pipeline I need this change.

2023-03-07 03:37 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/UserDefaultsStorage.swift
> +    func set(_ value: Any?, forKey key: String)
You're defining the protocol here, so let's get the protocol better designed with type safety.

2023-03-07 03:38 UTC, emlynmac commented on eng/pipelines/nightly.yml
> -      name: vsts-mac-1301-xcode-141
It's going to create a conflict when it comes time to merge.

2023-03-07 03:40 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/UserDefaultsStorage.swift
> +extension UserDefaults: UserDefaultsStorageProtocol {}
Which is a really bad idea; you're defining a protocol that happens to correspond to the public API of user defaults and then creating a empty inferface which happens to adhere to these exact methods.

Why do you need the protocol at all?

You just need to have the ability to operate on a specific UserDefaults object and have the ability to inject that instance as needed.

2023-03-07 03:45 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +    func insert(callStartedOn: Date, callId: String) {
There is no way to tell from the calling function whether this succeeded or failed.

2023-03-07 03:45 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +        callHistoryDispatchQueue.async {
Why do you want to process this on another queue?

2023-03-07 03:47 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +    private let callHistoryDispatchQueue = DispatchQueue(label: "CallHistoryDispatchQueue")
I would like to see the article, as I'm not sure why there's a queue here at all.
It seems it is used to run the insert, which may fail - and there's no way to ascertain if it failed.

Why do you need the queue - what problem are you solving with it?

2023-03-07 17:45 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
> +            let callHistory = callingViewModel.callHistory
The calculation logic should be moved to the VM

2023-03-07 17:46 UTC, vhuseinova-msft commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
> +    @ObservedObject var callingViewModel: CallingDemoViewModel
Do we need to use `callingViewModel` as `@ObservedObject` here?

2023-03-07 18:16 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallHistoryService.swift
> +        callHistoryDispatchQueue.async {
I'm wondering if we should use `sync` function here instead of `async`

2023-03-07 18:19 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Service/CallHistoryRepositoryTests.swift
> +        setExpectation.expectedFulfillmentCount = 4
`assertForOverFulfill` should be set to `true`

2023-03-07 18:21 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +        callHistoryDispatchQueue.async {
also, if it's done on a separate queue, it may need to be done in sync way

2023-03-07 18:41 UTC, emlynmac commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
> +            callHistoryMessage += "Call Ids:\n"
It's formatting a string for display - the logic here is something that could and should be shared; the view model would be the logical place to share the formatting logic, for the purpose of consistency and DRY design.

2023-03-07 18:42 UTC, emlynmac commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
> +    @State var callHistoryMessage: String = ""
It should be a property on the view model, as it is used in both UIKit and SwiftUI implementations and should be consistent.

2023-03-07 21:08 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallHistoryRecord.swift
> +    /// Local date call started on.
Date is not tied to a particular timezone.  Local should be removed here.
ref: https://developer.apple.com/documentation/foundation/date

2023-03-07 21:13 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +        return getAllAsDictionary()
This could be more succinctly writen:
```
    func getAll() -> [CallHistoryRecord] {
        return getAllAsDictionary()
            .map(CallHistoryRecord.init(callStartedOn:callIds:))
    }
   ```

2023-03-07 21:18 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +    private func cleanupOldRecords(_ historyRecords: [Date: [String]]) -> [Date: [String]] {
I would expect a `cleanup` function to remove the keys from the underlying storage.
This function is just a filter, which means that over time, the backing store is going to grow and grow.

2023-03-07 21:19 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallHistoryRecord.swift
> +    /// Local date call started on.
It is according to guidelines: https://azure.github.io/azure-sdk/ios_design.html#ios-request-options-types

2023-03-07 21:19 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/State/CallingState.swift
> +         callStartDate: Date? = nil) {
Maybe put the callID log error here?

2023-03-07 21:20 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallHistoryService.swift
> +    func recordCallHistory(callStartedOn: Date, callId: String) {
Can this be private?

2023-03-07 21:26 UTC, vhuseinova-msft commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Service/CallHistoryServiceTests.swift
> +        XCTAssertFalse(sut.recordCallHistoryWasCalled())
This unit test can be split into 2:
1) to check that the record call history wasn't called. THis can be checked with[ inverted expectations](https://developer.apple.com/documentation/xctest/xctestexpectation/2806573-inverted?language=objc)
2) to check that record call history was called with usual expectation + check that date and call id is the same as was sent in the test

the comment can be addressed in a separate PR

2023-03-07 21:30 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallHistoryRepositoryMocking.swift
> +                   userDefaults: UserDefaults())
This should not use UserDefaults() directly - create a non-persistent one from the test harness, as the CallHistoryRepositoryTests do

2023-03-07 21:30 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallHistoryService.swift
> +    func recordCallHistory(callStartedOn: Date, callId: String) {
Need to access from test mock. I believe there is not protected access level, nor alternative?

2023-03-07 21:33 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +    private func cleanupOldRecords(_ historyRecords: [Date: [String]]) -> [Date: [String]] {
a filtered out records are used in insert() method. This way we get rid of old records.

2023-03-07 21:39 UTC, emlynmac commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Data/CallHistoryRepository.swift
> +    private func cleanupOldRecords(_ historyRecords: [Date: [String]]) -> [Date: [String]] {
Ok, so the functionality is not very clear; the insert gets all, which actually gets a filtered list and then saves the updated list back.
Let's rename the cleanup function to `filterExpiredRecords`

While we're there, let's break out the 31 day hard-coded value to a variable.

2023-03-07 21:42 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Service/CallHistoryServiceTests.swift
> +        XCTAssertFalse(sut.recordCallHistoryWasCalled())
Noted in user story

2023-03-07 22:27 UTC, vhuseinova-msft approved these changes

2023-03-07 22:28 UTC, emlynmac approved these changes

2023-03-07 22:29 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/State/CallingState.swift
> +         callStartDate: Date? = nil) {
Task is created to address this.

2023-03-07 22:34 UTC, merged