[Feature] Introduce the LobbyOverlayViewModel with localization
Azure/communication-ui-library-ios pull request #64
Opened 2022-03-10 22:11 UTC by JoshuaLai

## Purpose
Introduce new view model to include localization provider. 
Using this to have dynamic localized string in lobby overlay

## Does this introduce a breaking change?
```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
Using the new settings page to change the language to something other than `en`
Join teams meeting 
Check new content in the lobby overlay.

2022-03-10 22:30 UTC, jimchou-dev approved these changes
Tested, LGTM

2022-03-10 22:30 UTC, jimchou-dev commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingView.swift
> +                LobbyOverlayView(viewModel: lobbyViewModel)
nitpick: maybe do it in one line without having a variable to be more consistent with the
`PrimaryButton(viewModel: viewModel.get___ViewModel())`

2022-03-10 22:50 UTC, JoshuaLai commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingView.swift
> +                LobbyOverlayView(viewModel: lobbyViewModel)
Applied

2022-03-11 18:28 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
> +        return LobbyOverlayViewModel(localizationProvider: localizationProvider)
Should we use the factory to generate the new subview models?

2022-03-11 18:28 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/LobbyOverlayViewModelTests.swift
> +        XCTAssertEqual(sut.title, "ABC")
"ABC"?

2022-03-11 22:38 UTC, JoshuaLai commented on AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/LobbyOverlayViewModelTests.swift
> +        XCTAssertEqual(sut.title, "ABC")
Yes in our mocking we hardcode it to "ABC" so this ensures that if the client passes in something that will override the localization dictionary we are honouring it

2022-03-11 22:39 UTC, JoshuaLai commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
> +        return LobbyOverlayViewModel(localizationProvider: localizationProvider)
I was debating this as well. IMO because we only have lobby in the call view I think its fine to have in created in the `CallingViewModel` if in the future we find we need to have the lobby in other places in the flow than maybe we can move it to the factory.

2022-03-11 22:54 UTC, waynemo requested changes

2022-03-11 22:54 UTC, waynemo commented on AzureCommunicationUI/AzureCommunicationUI/Presentation/SwiftUI/Calling/CallingViewModel.swift
> +        return LobbyOverlayViewModel(localizationProvider: localizationProvider)
Even if it's only used here, I think it will be better to follow the pattern of using the factory. Otherwise, we might cause confusion in the future when new view models are needed.

2022-03-11 22:54 UTC, waynemo commented on AzureCommunicationUI/AzureCommunicationUITests/Presentation/Calling/LobbyOverlayViewModelTests.swift
> +        XCTAssertEqual(sut.title, "ABC")
It might cause some confusion at first glance why we're validating against "ABC". Could we use something the resembles what the actual string might be? 
e.g. "Overlay Title"

2022-03-14 18:02 UTC, AmyL219 commented on AzureCommunicationUI/AzureCommunicationUITests/LocalizationProviderMocking.swift
> +        return key.rawValue
This makes much sense than returning `ABC`. If all the key return same value `ABC`, how can we test if we have fetched the value with correct StringKey input?

2022-03-14 18:10 UTC, AmyL219 approved these changes

2022-03-14 20:06 UTC, merged