[Feature][Calling] Skip Setup Screen
Azure/communication-ui-library-ios pull request #642
Opened 2023-03-29 19:10 UTC by ShaunaSong

## Purpose

* skip setup screen 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull request checklist

This PR has considered:
- [ ] Color Theming
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] View Data Injection
- [ ] Demo App UI/UX update

## How to Test

* Open...
* Click on...

## What to Check

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

## Other Information

2023-03-29 21:57 UTC, Mohtasim approved these changes, later dismissed

2023-03-29 23:19 UTC, pavelprystinka requested changes

2023-03-29 23:19 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/LocalOptions.swift
> +                startWithCameraOn: Bool? = false,
all these values by default should be nil

2023-03-29 23:36 UTC, pavelprystinka requested changes

2023-03-29 23:36 UTC, pavelprystinka commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/EnvConfig.swift
> +    @Published var micDefault: Bool = false
Let's keep naming consistent - startWithCameraOn format for all fields

2023-03-29 23:41 UTC, pavelprystinka requested changes

2023-03-29 23:41 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/StoreExtensions.swift
> +        localOptions: LocalOptions
I think we should not pass here a whole LocalOptions. It only needs startWithCameraOn, startWithMicrophoneOn and skipSetupScreen

2023-03-29 23:51 UTC, ShaunaSong commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/StoreExtensions.swift
> +        localOptions: LocalOptions
Updated

2023-03-30 16:44 UTC, pavelprystinka requested changes

2023-03-30 16:44 UTC, pavelprystinka commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/EnvConfig.swift
> +    @Published var startWithMicophoneOn: Bool = false
There is a typo.

2023-04-05 16:51 UTC, Mohtasim approved these changes, later dismissed

2023-04-05 17:03 UTC, pavelprystinka submitted a review, later dismissed

2023-04-05 18:36 UTC, pavelprystinka approved these changes

2023-04-05 18:43 UTC, Mohtasim approved these changes

2023-04-05 18:44 UTC, merged