[Calling][Feature] Update release version
Azure/communication-ui-library-ios pull request #645
Opened 2023-03-30 18:10 UTC by ShaunaSong

## Purpose

* update the version into 1.3.0 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull request checklist

This PR has considered:
- [ ] Color Theming
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] View Data Injection
- [ ] Demo App UI/UX update

## How to Test

* Open...
* Click on...

## What to Check

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

## Other Information

2023-04-05 16:37 UTC, Mohtasim approved these changes, later dismissed

2023-04-06 05:55 UTC, jpeng-ms commented
please remove the the python cache file from this PR

2023-04-06 16:55 UTC, Mohtasim submitted a review, later dismissed

2023-04-06 16:56 UTC, Mohtasim commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
> +- `LocalOptions(skipSetupScreen: Bool?)` to skip the setup screen and directly join the call. [642](https://github.com/Azure/communication-ui-library-ios/pull/642)
As far as I remember, we ( with previous iOS calling team) agreed to not include the PR in the Changelog.

2023-04-06 17:03 UTC, ShaunaSong commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
> +- `LocalOptions(skipSetupScreen: Bool?)` to skip the setup screen and directly join the call. [642](https://github.com/Azure/communication-ui-library-ios/pull/642)
Still have PR link for chat as well

2023-04-06 17:04 UTC, pavelprystinka requested changes

2023-04-06 17:04 UTC, pavelprystinka commented on scripts/__pycache__/composite.cpython-310.pyc
Please delete this file

2023-04-06 17:04 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.podspec
> +  spec.dependency             'AzureCommunicationCalling', '2.3.0-beta.1'
We can not use beta SDK for UI library GA

2023-04-06 17:10 UTC, ShaunaSong commented on scripts/__pycache__/composite.cpython-310.pyc
Deleted

2023-04-06 17:10 UTC, ShaunaSong commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.podspec
> +  spec.dependency             'AzureCommunicationCalling', '2.3.0-beta.1'
Change back

2023-04-06 17:28 UTC, pavelprystinka approved these changes

2023-04-06 19:03 UTC, Mohtasim approved these changes

2023-04-06 19:05 UTC, merged