Add 1 to N calling support
Azure/communication-ui-library-ios pull request #754
Opened 2023-10-20 10:24 UTC by LovBhagat-ms

## Purpose
Add one to N support 

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull request checklist

This PR has considered:
- [ ] Color Theming
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] View Data Injection
- [ ] Demo App UI/UX update

## How to Test
Try to use 1:N calling in Swift UI 

* Open...
* Click on...

## What to Check

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

## Other Information

2023-10-20 16:45 UTC, pavelprystinka requested changes

2023-10-20 16:45 UTC, pavelprystinka commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/DemoInputTypes.swift
> +    case oneToNCalling
Should it be oneToNCall? similar to groupCall (not groupCalling)

2023-10-20 16:45 UTC, pavelprystinka commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/EnvConfig.swift
> +    case oneToNCallingId
that is a call ID, not calling ID oneToNCallId

2023-10-20 16:45 UTC, pavelprystinka commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
> +                Text("1:N Calling").tag(MeetingType.oneToNCalling)
1:N Calling -> 1:N Call

2023-10-20 16:45 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
> +        if let locator = remoteOptions.locator {
What is going to happen if Contoso put in remoteOptions.locator and remoteOptions.startCall?
It is invalid scenario and we need to produce an error or at leas log error to the log, otherwise they may be confused.

Take launch(callConfiguration, localOptions: localOptions) out of if-else to avoid duplication

2023-10-20 16:45 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallConfiguration.swift
> +    init(startCall: CallCompositeStartCallOptions,
rename parameter to startCallOptions

2023-10-20 16:45 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/RemoteOptions.swift
> +    public var startCall: CallCompositeStartCallOptions?
startCall -> startCallOptions

2023-10-20 16:45 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/RemoteOptions.swift
> +// CallComposite Start Call for 1:N Calling
"CallComposite Start Call for 1:N Calling" -> "CallComposite start call options for 1:N call"

2023-10-20 16:45 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/RemoteOptions.swift
> +public struct CallCompositeStartCallOptions {
We do not need to prefix on iOS: CallCompositeStartCallOptions -> StartCallOptions

2023-10-20 16:45 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/RemoteOptions.swift
> +    public var partipants: [String]
need a comment to the property.

2023-10-20 16:45 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/RemoteOptions.swift
> +    /// 1:N Start Call Object
"1:N Start Call Object" -> "The 1:N start call options."

2023-10-20 16:45 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/RemoteOptions.swift
> +    public init(for startCall: CallCompositeStartCallOptions,
startCallOptions

2023-10-20 16:45 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
> +        let callParticipants = callConfiguration.participants {
Indentation does not look right

2023-10-20 16:45 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
> +            throw CallCompositeInternalError.callJoinFailed
Just curious: did we consider introducing startCallFailed error? Should it be a new error?

2023-10-23 04:55 UTC, iaulakh commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/EnvConfig.swift
> +    case oneToNCallingId
please change to participants id's

2023-10-23 04:58 UTC, iaulakh commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/RemoteOptions.swift
> +    public var locator: JoinLocator?
plese keep this as let and initialize as null in other constructors

2023-10-23 05:00 UTC, iaulakh commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallConfiguration.swift
> +        }
please keep string list here, we can convert this in calling sdk wrapper

2023-10-23 05:02 UTC, iaulakh commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
> +                let startCallOptions = CallCompositeStartCallOptions(partipants: [link])
please accept comma separated id's so that in test app we can dial multiple participants

2023-10-23 07:46 UTC, LovBhagat-ms commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/DemoInputTypes.swift
> +    case oneToNCalling
done

2023-10-23 07:46 UTC, LovBhagat-ms commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/EnvConfig.swift
> +    case oneToNCallingId
done

2023-10-23 07:47 UTC, LovBhagat-ms commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
> +                Text("1:N Calling").tag(MeetingType.oneToNCalling)
done

2023-10-23 08:18 UTC, LovBhagat-ms commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
> +                let startCallOptions = CallCompositeStartCallOptions(partipants: [link])
done

2023-10-23 08:20 UTC, LovBhagat-ms commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
> +        if let locator = remoteOptions.locator {
done

2023-10-23 08:21 UTC, LovBhagat-ms commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallConfiguration.swift
> +    init(startCall: CallCompositeStartCallOptions,
done

2023-10-23 08:26 UTC, LovBhagat-ms commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallConfiguration.swift
> +        }
done

2023-10-23 08:31 UTC, LovBhagat-ms commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/RemoteOptions.swift
> +// CallComposite Start Call for 1:N Calling
done

2023-10-23 08:32 UTC, LovBhagat-ms commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/RemoteOptions.swift
> +public struct CallCompositeStartCallOptions {
done, i renamed it to StartCallOptionsOneToNCall, as startCallOptions is already used by ACS SDK and to avoid confusion using some other name

2023-10-23 08:34 UTC, LovBhagat-ms commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/RemoteOptions.swift
> +    public var partipants: [String]
done

2023-10-23 08:44 UTC, LovBhagat-ms commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/RemoteOptions.swift
> +    public var locator: JoinLocator?
done

2023-10-23 08:45 UTC, LovBhagat-ms commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/RemoteOptions.swift
> +    /// 1:N Start Call Object
done

2023-10-23 08:45 UTC, LovBhagat-ms commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/RemoteOptions.swift
> +    public var startCall: CallCompositeStartCallOptions?
done

2023-10-23 08:45 UTC, LovBhagat-ms commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/RemoteOptions.swift
> +    public init(for startCall: CallCompositeStartCallOptions,
done

2023-10-23 08:46 UTC, LovBhagat-ms commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
> +        let callParticipants = callConfiguration.participants {
done

2023-10-23 08:47 UTC, LovBhagat-ms commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
> +            throw CallCompositeInternalError.callJoinFailed
Not for now, @iaulakh , i think we have discussion about it.
Thanks for pointing it out @pavelprystinka

2023-10-23 19:27 UTC, pavelprystinka approved these changes

2023-10-25 21:32 UTC, iaulakh approved these changes

2023-10-25 21:32 UTC, merged