[Calling][Feature] Merging with develop branch after UFD feature
Azure/communication-ui-library-ios pull request #755
Opened 2023-10-20 23:54 UTC by lucianopa-msft

## Purpose

* ...

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull request checklist

This PR has considered:
- [x] Color Theming
- [x] iOS supported versions (all major versions greater than or equal current target deployment version)
- [x] VoiceOver and Keyboard Accessibility
- [x] Internationalization and Right to Left layouts
- [x] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [x] View Data Injection
- [x] Demo App UI/UX update

## How to Test

* Open...
* Click on...

## What to Check

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

## Other Information

2023-10-21 00:00 UTC, iaulakh requested changes
Please add changelog feature

2023-10-23 16:58 UTC, iaulakh approved these changes

2023-10-23 16:59 UTC, ShaunaSong approved these changes

2023-10-23 19:22 UTC, pavelprystinka approved these changes

2023-10-24 22:54 UTC, merged