Feature/1.6.0 enhanced support audio only
Azure/communication-ui-library-ios pull request #794
Opened 2024-02-07 07:10 UTC by ahammer

## Purpose

* ...

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull request checklist

This PR has considered:
- [ ] Color Theming
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] View Data Injection
- [ ] Demo App UI/UX update

## How to Test

* Open...
* Click on...

## What to Check

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

## Other Information

2024-02-09 18:48 UTC, pavelprystinka requested changes

2024-02-09 18:48 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/DebugInfo.swift
> +    public let callingUIVersion: String
Please add missing documentation

2024-02-09 18:49 UTC, pavelprystinka requested changes

2024-02-09 18:49 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/LocalOptions.swift
> +                avMode: CallCompositeAvMode = .normal) {
Please add documentation to Parameters. We apparently did already miss a few.

2024-02-10 01:41 UTC, ahammer commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/LocalOptions.swift
> +                avMode: CallCompositeAvMode = .normal) {
This file has had it's documentation updated now

2024-02-12 18:44 UTC, iaulakh commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeAvMode.swift
> +public enum CallCompositeAvMode {
misisng doc for public API

2024-02-12 18:47 UTC, iaulakh reviewed
Adam, t will be good to add few UI tests

2024-02-12 20:09 UTC, ahammer commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeAvMode.swift
> +public enum CallCompositeAvMode {
Thanks, will add now.

2024-02-12 21:11 UTC, pavelprystinka submitted a review, later dismissed

2024-02-12 21:36 UTC, pavelprystinka approved these changes

2024-02-15 18:22 UTC, iaulakh approved these changes

2024-02-15 18:34 UTC, pavelprystinka approved these changes

2024-02-15 18:35 UTC, merged