Leave call confirmation added
Azure/communication-ui-library-ios pull request #853
Opened 2024-04-25 03:55 UTC by DivyaMittal528

## Purpose

* ...

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull request checklist

This PR has considered:
- [ ] Color Theming
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] View Data Injection
- [ ] Demo App UI/UX update

## How to Test

* Open...
* Click on...

## What to Check

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

## Other Information

2024-04-29 17:46 UTC, iaulakh commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarViewModel.swift
> +            self.isConfirmLeaveListDisplayed = true
where is this value used?

2024-04-30 03:19 UTC, DivyaMittal528 commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarViewModel.swift
> +            self.isConfirmLeaveListDisplayed = true
isConfirmLeaveListDisplayed this value used to show leave call alert

2024-05-01 23:34 UTC, pavelprystinka requested changes

2024-05-01 23:34 UTC, pavelprystinka commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
> +        let barOptions = CallScreenControlBarOptions(leaveCallConfirmationMode:
We have two Views to launch call composite: this one, and CallingDemoViewController. Could you please add callScreenOptions there as well.

2024-05-01 23:34 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/LeaveCallConfirmationMode.swift
> +public enum LeaveCallConfirmationMode {
We can not use enum in the public API. Please see CallState or ParticipantRole for example.
Here is a documentation:
https://azure.github.io/azure-sdk/ios_design.html#enumerations

2024-05-02 18:39 UTC, pavelprystinka approved these changes

2024-05-02 18:40 UTC, ShaunaSong approved these changes

2024-05-02 18:40 UTC, merged