[Calling][Feature] Closed Captions
Azure/communication-ui-library-ios pull request #910
Opened 2024-07-16 17:31 UTC by ShaunaSong

## Purpose

* ACS & Teams Captions Support 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull request checklist

This PR has considered:
- [ ] Color Theming
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] View Data Injection
- [ ] Demo App UI/UX update

## How to Test

* Open...
* Click on...

## What to Check

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

## Other Information

2024-07-17 23:31 UTC, ahammer commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewModel.swift
> +            DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
Logging?

Side effect?
updateCaptionOptions should be updating the relevant bindings in the VM and that's it. It shouldn't be performing any mutation that wasn't triggered by an action.

Is this the best place to dispatch .startRequested?

If you need action->[actions...], Middleware is good for that.

2024-07-17 23:34 UTC, ahammer commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/DrawerListContent.swift
> +// Helper to inflate DrawerListItemViewModel into a drawer
There should be another, updated version of this class, with more types of VM's supported etc. I may have refactored the name.

2024-07-23 18:58 UTC, pavelprystinka requested changes

2024-07-23 18:58 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeOptions.swift
> +                userId: CommunicationIdentifier? = nil
please add userId to the documentation

2024-07-23 18:58 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CaptionOptions.swift
> +    public init(captionsOn: Bool = false, spokenLanguage: String = "") {
`spokenLanguage: String` should be nullable with default value nil.
An empty string is a string. But there is no language that can be resolved from empty string. Absents of value should be represented by nil

2024-07-23 18:58 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/LocalOptions.swift
> +    ///   - captionsOption: Configuration for captions
captionsOptions need to be defined after audioVideoMode in docs

2024-07-23 18:58 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CaptionOptions.swift
> +    var captionsOn: Bool
captionsOn and spokenLanguage should be let, not var

2024-07-23 18:58 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/es-ES.lproj/Localizable.strings
> +"AzureCommunicationUICalling.SetupView.Button.StartCall"="Start call";
Why do we revert localizations? I see a lot "AzureCommunicationUICalling.SetupView.Button.StartCall" reverted in the PR.

2024-07-23 18:58 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactoryProtocols.swift
> +                                    iconName: CompositeIcon? = CompositeIcon.none,
no need for explicit CompositeIcon

2024-07-23 18:58 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Captions/CaptionsListViewModel.swift
> +    private var state: AppState
Why do we need to keep state? Doesn't look necessary.

2024-07-23 18:58 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/State/CaptionsState.swift
> +    var activeSpokenLanguage: String?
does it need suffix `active` is there inactive spoken language? Redux state is by itself represents what is active/current.

Would it be enough to name it `spokenLanguage`

same for `activeCaptionLanguage`

2024-07-23 18:58 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/CaptionsReducer.swift
> +            newState.isEnabled = true
This is weird looking. Should action be .enable? Or setEnable(bool).

2024-07-23 18:58 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/CaptionsReducer.swift
> +            newState.isEnabled = false
There should not be such logic in the Reducer. Middleware should make such decisions and call dispatch action (.setEnable(bool))

2024-07-23 18:58 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKEventsHandler.swift
> +        if currentStatus == .connected {
Why do we need to this captions change on `currentStatus == .connected`? Is how SDK team suggested in their documentation?
Why it can not be done as all other features in the CallingSDKWrapper.setupFeatures()

2024-07-23 22:03 UTC, iaulakh commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
> +            callingSDKWrapper: callingSdkWrapper
Please test if start call, start captions, end call, start captions again works fine.

2024-07-23 22:03 UTC, iaulakh commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeError.swift
> +    /// Captions not active. To change spoken, captions language, captions must be active.
caption language

2024-07-23 22:05 UTC, iaulakh commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings
> +"AzureCommunicationUICalling.Captions.ActionError.ChangeCaptionsLanguage"="Unable to change captions language";
caption langauge

2024-07-23 22:09 UTC, iaulakh commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Middleware/CallingMiddlewareHandler.swift
> +    func startCaptions(state: AppState, dispatch: @escaping ActionDispatch, language: String) -> Task<Void, Never> {
on error, do we want to turn off captions checkbox?

2024-07-24 16:53 UTC, ShaunaSong commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Middleware/CallingMiddlewareHandler.swift
> +    func startCaptions(state: AppState, dispatch: @escaping ActionDispatch, language: String) -> Task<Void, Never> {
Toggle will be on when the captions start successfully

2024-07-24 17:25 UTC, ShaunaSong commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKEventsHandler.swift
> +        if currentStatus == .connected {
Yes, it is suggested by SDK Team to get the default support languages.

We don't have the event for default languages.

2024-07-30 17:39 UTC, iaulakh commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Model/CallCompositeCaptionsData.swift
> +    var id: Date { timestamp }
what is the use of this id?

2024-07-30 17:44 UTC, iaulakh commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Captions/CaptionsErrorViewModel.swift
> +        invalidateTimer()
I think on dismiss error should be cleared in redux so that on screen rotation etc, error is not displayed?

2024-07-30 17:46 UTC, iaulakh commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
> +                }
I think we need to pass all errors to middleware. 
Show alert for all errors- ui
Notify Contoso only for above errors.

2024-07-30 17:47 UTC, iaulakh commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Middleware/CallingMiddlewareHandler.swift
> +                dispatch(.captionsAction(.error(errors: .captionsFailedToStart)))
How we decide errors for which Contoso should be notified?

2024-07-30 17:50 UTC, ShaunaSong commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Model/CallCompositeCaptionsData.swift
> +    var id: Date { timestamp }
this ID is used to make captionsData to be identifiable, which will help Ui to scroll and identify

2024-07-30 18:07 UTC, ShaunaSong commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Captions/CaptionsErrorViewModel.swift
> +        invalidateTimer()
Hey Inderpal, this is the same logic as the BottomToastViewModel for call diagnostics.  Maybe I could refactor two together in the separate PR.

2024-08-02 17:37 UTC, iaulakh approved these changes

2024-08-05 20:15 UTC, pavelprystinka approved these changes

2024-08-06 17:45 UTC, merged