[Calling][Bug] 3859662_String Diffference in SnackBar
Azure/communication-ui-library-ios pull request #944
Opened 2024-08-30 16:37 UTC by inancyGit

=> Different messages depending on platform when Client completely lost connection and didn't reconnect Changed string in ios.

## Purpose

* ...

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull request checklist

This PR has considered:
- [ ] Color Theming
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] View Data Injection
- [ ] Demo App UI/UX update

## How to Test

* Open...
* Click on...

## What to Check

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

## Other Information

2024-08-30 19:11 UTC, pavelprystinka requested changes

2024-08-30 19:11 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings
> +"AzureCommunicationUICalling.SnackBar.Text.ErrorCallEnd"="You may have been removed from the meeting, or lost your connection. Try to join again.";
We have `ErrorCallEvicted` for the `may have been removed` - do you get ErrorCallEnd message when user is removed from the call? If so, it is not correct.
Can we distinguish when call is disconnected due to network issues? Could you please check what we receive in the call end reason from the SDK (there is code and subcode).
`ErrorCallEnd` should be reserved to the unknown call end reason only.

2024-08-30 20:09 UTC, inancyGit commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings
> +"AzureCommunicationUICalling.SnackBar.Text.ErrorCallEnd"="You may have been removed from the meeting, or lost your connection. Try to join again.";
The code which I get in log is : **_Subscription cancelled with Error Code: callEndFailed_**  and for CallEvicted: This is the message 
"AzureCommunicationUICalling.SnackBar.Text.ErrorCallEvicted"="You were removed from the call.";

2024-09-03 17:17 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings
> +"AzureCommunicationUICalling.SnackBar.Text.ErrorCallEnd"="You may have been removed from the meeting, or lost your connection. Try to join again.";
Discussed:
"You were removed from the call due to an error or your lost connection. Try to join again."

2024-09-03 19:51 UTC, pavelprystinka requested changes

2024-09-03 19:51 UTC, pavelprystinka commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-GB.lproj/Localizable.strings
> +"AzureCommunicationUICalling.SnackBar.Text.ErrorCallEnd"="You may have been removed from the meeting, or lost your connection. Try to join again.";
Please align it with Android message.

2024-09-03 19:54 UTC, inancyGit commented on AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-GB.lproj/Localizable.strings
> +"AzureCommunicationUICalling.SnackBar.Text.ErrorCallEnd"="You may have been removed from the meeting, or lost your connection. Try to join again.";
@pavelprystinka  I aligned it in the file Localizable.strings(English) It is generic one. Hence, it reflects there.

2024-09-05 16:17 UTC, iaulakh submitted a review, later dismissed

2024-09-05 17:02 UTC, Mohtasim submitted a review, later dismissed

2024-09-05 23:10 UTC, ShaunaSong approved these changes

2024-09-05 23:28 UTC, Mohtasim approved these changes

2024-09-06 16:19 UTC, pavelprystinka approved these changes

2024-09-06 16:20 UTC, merged