[Calling][Release] Update the version to 1.13.0
Azure/communication-ui-library-ios pull request #998
Opened 2024-11-26 18:46 UTC by ShaunaSong

## Purpose

* Update the release version to 1.13.0

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Pull request checklist

This PR has considered:
- [ ] Color Theming
- [ ] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] View Data Injection
- [ ] Demo App UI/UX update

## How to Test

* Open...
* Click on...

## What to Check

| Before                                       | After                                      |
|----------------------------------------------|--------------------------------------------|
| Screenshot or description before this change | Screenshot or description with this change |

## Other Information

2024-11-26 19:46 UTC, pavelprystinka requested changes

2024-11-26 19:46 UTC, pavelprystinka commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
> +					"$(FRAMEWORK_SEARCH_PATHS)",
I think this change should not be here? Is it leftover from using local framework?

2024-11-26 19:51 UTC, ShaunaSong commented on AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
> +					"$(FRAMEWORK_SEARCH_PATHS)",
I am trying to fix the unit test failed for pipeline, 

But it seems not working, will revert the changes

2024-11-26 21:16 UTC, jamchengms approved these changes

2024-11-27 20:09 UTC, ShaunaSong commented
Closed as the unit test always failed

2024-11-27 20:09 UTC, closed without merging